### ISSUE TITLE
Provide the current speed level as attribute

### ISSUE THREAD

**Issue by jacekpaszkowski** [syssi/xiaomi_fan#1]
Hi syssi,
Is it possible to add mode (one of speed_list: off,Level 1,Level 2,Level 3,Level 4) to device attributes?

Thank you for this component!

Regards,
Jacek

**Comment by syssi** [comment]
The `fan.set_speed` supports a fan speed in percent (0 ... 100%) already.

**Comment by jacekpaszkowski** [comment]
I understand but i'm talki about status. Device has no current mode attribute.
Now i have to create template sensor to map speed to mode :)

**Comment by syssi** [comment]
Done. Please give it a try! :-)
