### ISSUE TITLE
Add dmaker.fan.1c support

### ISSUE THREAD

**Issue by Mohannadsharief** [syssi/xiaomi_fan#101]
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.1c

**Comment by syssi** [comment]
This device model wasn't supported ever. Did you use another `model` at your configuration at the past?

**Comment by syssi** [comment]
A fork which supports the model at the moment: https://github.com/damianpasek/xiaomi_fan

A first step to support the device offically: https://github.com/rytilahti/python-miio/pull/1012

**Comment by syssi** [comment]
Duplicate of #85.
