### ISSUE TITLE
Integration seems to be broken after update to Home Assistant 2021.4.1

### ISSUE THREAD

**Issue by jemmerich** [syssi/xiaomi_fan#105]
After update to Home Assistant 2021.4.1 integration does not work anymore

Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_fan/fan_1c.py:113 
Integration: Fan (documentation, issues) 
First occurred: 21:22:36 (1 occurrences) 
Last logged: 21:22:36

Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 303, in async_setup_platform
    fan = Fan1C(host, token)
  File "/config/custom_components/xiaomi_miio_fan/fan_1c.py", line 113, in __init__
    super().__init__(_MAPPING, ip, token, start_id, debug, lazy_discover)
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 150, in __init__
    self._protocol = MiIOProtocol(
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 43, in __init__
    self.token = bytes.fromhex(token)
ValueError: non-hexadecimal number found in fromhex() arg at position 3

**Comment by johnjoemorgan** [comment]
On upgrade to 2021.4.x for these 2 fans:

   NAME:     Aunt Fanny
   ID:       240xxxx4
   IP:       192.168.0.xx
   TOKEN:    82540fxxxxxxxxxxxxxxx5e2
   MODEL:    dmaker.fan.1c
   ---------
   NAME:     Fanny
   ID:       721xxxx1
   IP:       192.168.0.1.xxx
   TOKEN:    1b927xxxxxxxxxxxxxx8578ff6f
   MODEL:    zhimi.fan.sa1

The zhimi.fan.sa1 continues to respond as before but he dmaker.fan.1c is unavailable.

Looking at the github notes I see that the zhimi is under airpurifier code and dmaker is in the fan code.

Currently I have downgraded to 2021.3.x but I can upgrade again so I can give you exact config files and results 

I am based in Asia/PH GMT-8

Let me know, as I'm not a coder this is the best way I can contribute.

**Comment by syssi** [comment]
Please update the custom component and give it another try.

**Comment by jemmerich** [comment]
Reinstalled the component in HACS, same error

Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_fan/fan_1c.py:113 
Integration: Fan (documentation, issues) 
First occurred: 22:24:32 (1 occurrences) 
Last logged: 22:24:32

Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 303, in async_setup_platform
    fan = Fan1C(host, token)
  File "/config/custom_components/xiaomi_miio_fan/fan_1c.py", line 113, in __init__
    super().__init__(_MAPPING, ip, token, start_id, debug, lazy_discover)
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 150, in __init__
    self._protocol = MiIOProtocol(
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 43, in __init__
    self.token = bytes.fromhex(token)
ValueError: non-hexadecimal number found in fromhex() arg at position 3

**Comment by syssi** [comment]
@jemmerich The file `fan_1c.py` isn't part of this custom component. It looks like you are using this fork:

https://github.com/damianpasek/xiaomi_fan

The `dmaker.fan.c1` isn't supported at this custom component right now.

**Comment by JeroLajHub** [comment]
I am too using this fork. His author already wrote to you somewhere in your forum to let you implement it in your custom component, if I am not wrong. Do you consider this, as we would have the both advantages in one place : your active development and Fan 1C support ? Best regards.

Right now no fan custom component (fan or airpurifier) works in my updated home assistant for 1C. I have no other Xiamoi fan to compare. I am continuing to try with you lastest udgrades in the last hour.

**Comment by jemmerich** [comment]
used to work very reliably until the last update...

**Comment by syssi** [comment]
I've prepared a PR to add the device support of the `dmaker.fan.c1` to `python-miio`. As soon the device is available there I can add it to this custom component.

**Comment by JeroLajHub** [comment]
> I've prepared a PR to add the device support of the `dmaker.fan.c1` to `python-miio`. As soon the device is available there I can add it to this custom component.

That(s great ! Thanks.

https://github.com/syssi/xiaomi_fan/issues/101

**Comment by syssi** [comment]
I'm closing this issue because it's unrelated to this custom component.
