### ISSUE TITLE
NameError: name 'async_add_entities' is not defined

### ISSUE THREAD

**Issue by dxxxm** [syssi/xiaomi_fan#106]
```
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_fan/fan.py:329
Integration: Fan (documentation, issues)
First occurred: 8:57:23 PM (2 occurrences)
Last logged: 8:57:23 PM

Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 329, in async_setup_platform
    async_add_entities([device], update_before_add=True)
NameError: name 'async_add_entities' is not defined
```

`Xiaomi Mi Smart Pedestal Fan Version 0.3.0`

## System Health

version | core-2021.4.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.10.0-5-amd64
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4798
Installed Version | 1.11.3
Stage | running
Available Repositories | 839
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux bullseye/sid
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.9
docker_version | 20.10.5
disk_total | 27.1 GB
disk_used | 8.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | InfluxDB (4.0.4), Grafana (6.3.0), AppDaemon 4 (0.5.2), Let's Encrypt (4.11.0), Terminal & SSH (9.1.0), ESPHome (1.16.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 3
views | 8
mode | storage

</details>

`fan.py : line 271: async def async_setup_platform(hass, config, async_add_devices, discovery_info=None):`

if I am not mistaken the 3rd parameter should read:  `async_add_entities ` ?

**Comment by syssi** [comment]
Thanks for filing the issue. You are right! I've fixed the glitch.
