### ISSUE TITLE
Can't set speed

### ISSUE THREAD

**Issue by percy10442** [syssi/xiaomi_fan#107]
Unable to set the speed of dmaker.fan.p5 after update to Home Assistant 2021.4.5

**Comment by syssi** [comment]
What did you try exactly and what did HA respond?

**Comment by percy10442** [comment]
I tried to adjust the speed, but HA showed that the service fan/percentage execution failed.'fanp5' object has no attribute /set_direct_speed

This is a screenshot.
[https://drive.google.com/file/d/1Cp2k7en2w9JnjAEpseI8G4U81hgp4GJt/view?usp=sharing](url)

**Comment by syssi** [comment]
Fixed by 9600f5b2d1e5ef3c2e6a788631b30411ffff6437.

**Comment by percy10442** [comment]
Thank you for fixing the bug, but there are still errors in the pre_set mode from level1 to level3.HA showed that the service fan/set_preset_mode failed execution failed.

This is a screenshot.
https://drive.google.com/file/d/1eRBctqvIIoRDJTgwmrUCANhRd0vWVRiY/view?usp=sharing

**Comment by syssi** [comment]
I don't have access to the screenshot. Could you acknowledge the `set_percentage` service is working now? I will care about the `set_preset_mode` issue as soon I've access to the screenshot / error message.

**Comment by percy10442** [comment]
Sorry, I have opened the access to the screenshot.

**Comment by syssi** [comment]
I've fixed the issue and prepared a new release. Please give it a try!
