### ISSUE TITLE
cannot import name 'FanLesow' 

### ISSUE THREAD

**Issue by a0024** [syssi/xiaomi_fan#109]
Why this error occurs 
Platform error fan.xiaomi_miio_fan - cannot import name 'FanLesow' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)

Home Assistant 2021.4.6

**Comment by syssi** [comment]
Do you use additional custom components interfacing xiaomi miio devices? Please make sure every `manifest.json` is requiring the same (`0.5.5`) version of `python-miio`.

**Comment by a0024** [comment]
I change all requiring to 0.5.5
But still the same problem 
Is there ny way to know that the miio version loaded by ha is 0.5.5?

**Comment by a0024** [comment]
Problem solved after reinstall
