### ISSUE TITLE
Support for dmaker.fan.p15

### ISSUE THREAD

**Issue by rstein** [syssi/xiaomi_fan#111]
Hi!
I have recently purchased a 'Mi Smart Standing Fan Pro', model ZLBPSP01XY.
This device seems to not be supported:
`Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p15`

I would very much appreciate if you could add support for this device in your component. Please let me know if I can be of any assistance.

**Comment by Intelligenzbestie** [comment]
Me too, thought I could use a different (existing) template but to no avail

**Comment by Intelligenzbestie** [comment]
It's working for me (with the restrictions mentioned here: https://github.com/syssi/xiaomi_airpurifier/issues/141 using this in configuration.yaml:
fan:

platform: xiaomi_miio_airpurifier
name: Xiaomi Smart Fan Pro
host: IP address of the fan
token: xxx your token xxx
model: dmaker.fan.p11

I retrieved the token using this: https://github.com/Maxmudjon/Get_MiHome_devices_token/releases

**Comment by syssi** [comment]
Please create a new issue if an important feature is missing or broken.
