### ISSUE TITLE
dmaker.fan.1c issues

### ISSUE THREAD

**Issue by sokopower** [syssi/xiaomi_fan#117]
You close all issues about su dmaker.fan.1c but not work it for me.

 - platform: xiaomi_miio_fan
    name: fan 1
    host: 192.168.1.43
    token: 6119edd74d4e6a60fcbfc69c4XXXXXX
    model: dmaker.fan.1c

**verification said:**

_Invalid config for [fan.xiaomi_miio_fan]: value must be one of ['dmaker.fan.p10', 'dmaker.fan.p11', 'dmaker.fan.p5', 'dmaker.fan.p9', 'leshow.fan.ss4', 'zhimi.fan.sa1', 'zhimi.fan.v2', 'zhimi.fan.v3', 'zhimi.fan.za1', 'zhimi.fan.za3', 'zhimi.fan.za4'] for dictionary value @ data['model']. Got **'dmaker.fan.1c'.** (See ?, line ?)._

I have 2 units of Mi Smart Stading Fan model JLLDS01XY
Could you help me about dmaker.fan.1c, please?

Thank you very much! 🙏🏼
Regards

**Comment by syssi** [comment]
The device is supported of the development branch. A Home Assistant release (2021.5.1) is required before I can release this custom component. I hope the bugfix release of HA will happen this weekend.

**Comment by asifma** [comment]
core-2021.5.1 was just released. Tried this custom component using the dev branch.
But get this platform error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 853, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 493, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 12, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'FanC1' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)
```

**Comment by syssi** [comment]
If you see additional issues please report it here. As soon the device support looks good I will prepare new release of this custom component (installable via HACS).

**Comment by syssi** [comment]
Are you sure about your token and IP address?

**Comment by syssi** [comment]
Please check the developer tools (dev-state). Do you see a `fan.*` entity here? This custom component registers a single fan entity. Don't expect a device or integration showing up.

**Comment by JeroLajHub** [comment]
Mine are working perfectly with the previous yaml configuration ant token, those that worked with the previous fork and before Home Assistant breaking change. Now it is well back and official to this add-on. Great thanks !

**Comment by sokopower** [comment]
Works for me too !!
Thanks

**Comment by asifma** [comment]
Sorry, my fault. I think I restored the fan 2 weeks ago, thus a new token was generated.
And my config had an old one. Works perfectly now, thanks! :)

**Comment by marxkemp** [comment]
Yes, it's working here to. Thanks!

**Comment by syssi** [comment]
Cool! Let's close this issue. Feel free to create a new one if something isn't working as expected.
