### ISSUE TITLE
Missing Preset mode on 1C Fan

### ISSUE THREAD

**Issue by redphx** [syssi/xiaomi_fan#120]
![image](https://user-images.githubusercontent.com/96280/117530792-47c1a780-b009-11eb-8002-a1076232dacb.png)

FIxed by changing [this line](https://github.com/syssi/xiaomi_fan/blob/develop/custom_components/xiaomi_miio_fan/fan.py#L1043):
```python
# From
self._preset_modes = FAN_PRESET_MODES_1C
# To
self._preset_modes = list(FAN_PRESET_MODES_1C)
```

![image](https://user-images.githubusercontent.com/96280/117530806-58721d80-b009-11eb-99c1-401a2f8de0ee.png)

**Comment by syssi** [comment]
Good job! I will prepare a hotfix release. Do you like to provide a contribution by PR?

**Comment by redphx** [comment]
Thanks for the fix. I'm too lazy to create PR 😄
