### ISSUE TITLE
Cant add the repo to my H

### ISSUE THREAD

**Issue by iq860** [syssi/xiaomi_fan#125]
Hello 
I have just set up home assistant on my pi3 and every time I try to add the repo i get an error msg, what I do to fix that?

![image](https://user-images.githubusercontent.com/15311677/118104723-8b8f2500-b3ec-11eb-939e-acdebd245755.png)

**Comment by syssi** [comment]
This repository needs to be added as "Integration". This isn't a add-on repository.
