### ISSUE TITLE
error cannot import name 'Fan1C' from 'miio'

### ISSUE THREAD

**Issue by nesror** [syssi/xiaomi_fan#129]
yaml:
fan:
  - platform: xiaomi_miio_fan
    host: 192.168.31.139
    name: zhuwo_fan
    token:
  - platform: xiaomi_miio_fan
    host: 192.168.31.160
    name: ciwo_fan
    token:
    #model: dmaker.fan.p10
  - platform: xiaomi_miio_fan
    host: 192.168.31.204
    name: csnting_fan
    token:
    #model: dmaker.fan.p5

err msg:
Platform error fan.xiaomi_miio_fan - cannot import name 'Fan1C' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)

**Comment by syssi** [comment]
This happens if you've additional custom components installed interfacing Xiaomi devices / using `python-miio`. Please check the ´manifest.json` of all custom components. A `python-miio` version `>=0.5.6` must be required here. Please also make sure you are using the latest HA release.
