### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by pattyland** [syssi/xiaomi_fan#131]
Hi,

today I wondered why I'm still on version 0.3.3 in hacs despite 0.3.9 is published since weeks, but looking in the manifest.json of the 0.3.9 Release there it's still marked as 0.3.3. I didn't want to make a PR in case you got a plan I don't understand 😅

Greets
pattyland

**Comment by syssi** [comment]
Thanks for your feedback. I've pushed a bugfix release.
