### ISSUE TITLE
dmaker.fan.p15: fan.set_direction doesn't work

### ISSUE THREAD

**Issue by shlomki** [syssi/xiaomi_fan#139]
fan.set_direction doesn't work with model dmaker.fan.p15.

I've tried controlling it from the ui and calling the service directly (both with left/right and with forward/backward), but nothing happens.
Can it be related to the changes recently performed here?
https://github.com/syssi/xiaomi_fan/issues/116

**Comment by pooyashahidi** [comment]
can the problem maybe be similar to this one? https://github.com/syssi/xiaomi_fan/issues/136#issuecomment-864489697

**Comment by shlomki** [comment]
> can the problem maybe be similar to this one? [#136 (comment)](https://github.com/syssi/xiaomi_fan/issues/136#issuecomment-864489697)

Thanks! Definitely looks related and I'd like to try it out, but I'm not sure how to edit the underlying python-miio library that the component uses. Can you point me in the right direction?

**Comment by syssi** [comment]
Good catch!

**Comment by pooyashahidi** [comment]
> > can the problem maybe be similar to this one? [#136 (comment)](https://github.com/syssi/xiaomi_fan/issues/136#issuecomment-864489697)
> 
> Thanks! Definitely looks related and I'd like to try it out, but I'm not sure how to edit the underlying python-miio library that the component uses. Can you point me in the right direction?

hopefully this will solve the problem
https://github.com/rytilahti/python-miio/pull/1078

**Comment by shlomki** [comment]
hi @pooyashahidi , do you know if this is already included in HA 2021.7 ?
It still doesn't work for me

**Comment by pooyashahidi** [comment]
The pull request is merged in python-miio but If I'm not mistaken there are no new releases since may :/

**Comment by shlomki** [comment]
@syssi I've created a pull request to bump python-miio to 0.5.7, I've confirmed that it works as expected now.
