### ISSUE TITLE
智米新风可以支持一下吗

### ISSUE THREAD

**Issue by Yonsm** [syssi/xiaomi_fan#14]
感谢

**Comment by syssi** [comment]
Could you try to translate your issue?

**Comment by Yonsm** [comment]
I post a new issue on another Repo of yours. Please refer [https://github.com/syssi/xiaomi_airpurifier/issues/25](https://github.com/syssi/xiaomi_airpurifier/issues/25)

**Comment by syssi** [comment]
Duplicate.
