### ISSUE TITLE
Error while trying to add Smartmi Standing Fan 3 (zhimi.fan.za5)

### ISSUE THREAD

**Issue by nitobosch** [syssi/xiaomi_fan#141]
When trying to add my new Smartmi Standing Fan 3, configuring on the configuration.yaml and restaring my home assistant i'm getting the following error.

-------------------------------
Logger: homeassistant.components.fan
Source: util/percentage.py:21
Integration: Ventilador (documentation, issues)
First occurred: 13:54:25 (2 occurrences)
Last logged: 13:54:25

Error adding entities for domain fan with platform xiaomi_miio_fan
Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/fan/init.py", line 603, in state_attributes
data[ATTR_SPEED] = self.speed
File "/usr/src/homeassistant/homeassistant/components/fan/init.py", line 453, in speed
percentage = self.percentage
File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1155, in percentage
return ordered_list_item_to_percentage(FAN_SPEEDS_1C, self._preset_mode)
File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 21, in ordered_list_item_to_percentage
raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
ValueError: The item "None"" is not in "['Level 1', 'Level 2', 'Level 3']"

**Comment by tetiti20** [comment]
hello, I have exactly same problem...

**Comment by Aliskin-Papa** [comment]
Some here

**Comment by filikun** [comment]
Yeah I never got it to work. Does any of you have it on a different VLAN? I know that some Xiaomi stuff won't talk if the subnet differes.

**Comment by Aliskin-Papa** [comment]
> Yeah I never got it to work. Does any of you have it on a different VLAN? I know that some Xiaomi stuff won't talk if the subnet differes.

Local net, home, without any subnet/vpn.

**Comment by tetiti20** [comment]
No problem with last update

**Comment by filikun** [comment]
> No problem with last update

So you got it to work? Mine is still just unavailable with that error every time I reboot.

**Comment by tetiti20** [comment]
Yes I have remove line in yaml and delete fan entities. Update integration, restart HA.
Re add line in yaml and restart HA.
Now i can power it.

**Comment by filikun** [comment]
> 
> 
> Yes I have remove line in yaml and delete fan entities. Update integration, restart HA.
> Re add line in yaml and restart HA.
> Now i can power it.

Go it to work that way, thanks! Just make sure it's on the same subnet as HA.

**Comment by Aliskin-Papa** [comment]
> Yes I have remove line in yaml and delete fan entities. Update integration, restart HA.
> Re add line in yaml and restart HA.
> Now i can power it.

Yes, its work, but in the "attribute" only nothing:![SmartSelect_20210628-202129_Home Assistant.jpg](https://user-images.githubusercontent.com/76951399/123678173-aa3b6500-d84e-11eb-863f-31bf3884449b.jpg)

**Comment by tetiti20** [comment]
Yes. There's other issues

**Comment by syssi** [comment]
@Aliskin-Papa Which attribute do you miss in detail? Empty attributes aren't supported of your device in general.

**Comment by syssi** [comment]
@Aliskin-Papa Could you create a new issue and add the two screenshots there? I would like to close this one because it's solved (somehow) be the workaround: Removing & re-adding the component.

**Comment by Aliskin-Papa** [comment]
> @Aliskin-Papa Could you create a new issue and add the two screenshots there? I would like to close this one because it's solved (somehow) be the workaround: Removing & re-adding the component.

No problem.
