### ISSUE TITLE
Not able to add a dmaker.fan.p18 by making it appear a p10

### ISSUE THREAD

**Issue by Powablocks** [syssi/xiaomi_fan#142]
Hello,
I tried to add my new fan. I added this configuration : 

![image](https://user-images.githubusercontent.com/16413448/122654474-02d27a00-d14c-11eb-8bce-bab8a9d53cbc.png)
and I restarted but i have this message when trying to add the integration
![image](https://user-images.githubusercontent.com/16413448/122654461-e8989c00-d14b-11eb-8509-60f71e4bd04f.png)
The error translate to : unable to configure, model unknow.

Does someone have a solution please ?

**Comment by syssi** [comment]
The device will be official supported of the next release.
