### ISSUE TITLE
 zhimi.fan.za5 preset

### ISSUE THREAD

**Issue by tranductho** [syssi/xiaomi_fan#145]
im using zhimi.fan.za5, but there are on 3 preset from 1-3. In fact za5 has 4 level from 1-4. I read the py code:

```
FAN_PRESET_MODES_ZA5 = FAN_PRESET_MODES_1C
FAN_SPEEDS_ZA5 = FAN_SPEEDS_1C
```
 That's mean ZA5 preset the same with 1C, I think this isn't correct. ZA5 has 4 levels totally.

How can I fix?

**Comment by filikun** [comment]
Yeah I have this issue as well, have a look [here ](https://github.com/syssi/xiaomi_fan/issues/147#issuecomment-869585670)

**Comment by syssi** [comment]
Let's close this. Please subscribe #151.
