### ISSUE TITLE
Installation and parameter setting (almost) doesn´t work 

### ISSUE THREAD

**Issue by RonBln** [syssi/xiaomi_fan#146]
Even if I´m really grateful about this integration, I have to state that it´s only literally working. Here is my setting:

1. Smartmi Standing Fan 3 (zhimi.fan.za5)
2. Newest version of Home Assistant (core-2021.6.6)

First of all the installation through HACS is not working properly. It´s possible to install the repository in HACS, but once you try adding it as a custom integration, it wouldn't show up in the "New integrations" selection screen (even after several re-boots).

Second, once you install it manually, it´s more or less only possible turning the fan on/off. Almost all other settings like Oscillation angle, Natural mode (on, off) etc. are being ignored.

**Comment by syssi** [comment]
Could you provide screenshots? This custom component must be setup via configuration.yaml. There is no config-flow. This component is represented as `fan` entity. There is no integration / device exposed. I looks like you are talking about the official component.

**Comment by RonBln** [comment]
Always happy to help :) So this is how it looks in the HACS "explorer"
![Xiaomi_Fan_integration](https://user-images.githubusercontent.com/53210471/123333012-853ead80-d541-11eb-91ae-3ef9494a6ddc.png)

And this is what it says in the Readme of your repository
![install](https://user-images.githubusercontent.com/53210471/123333086-9982aa80-d541-11eb-9cd0-8fd3927a2f7e.png)

And that exactly is not happening.

**Comment by syssi** [comment]
I will remove this paragraph. It's outdated. There was a day this component wasn't part of the hacs-default repositories. It was important to add the repository to hacs manually. As soon this repo was added you have to go to the "integration" section of HACS and install the custom component. HACS uses the term "integration" here.

This custom component still requires some configuration at the `configuration.yaml`. If no configuration is added here the component doesn't get loaded.

**Comment by RonBln** [comment]
Great, that makes it much easier to understand and will avoid confusion 👍  

But for me the bigger problem actually is, that all of the `xiaomi_miio_fan` services doesn´t seem to work (at least for my 
Smartmi Standing Fan 3 | zhimi.fan.za5)

**Comment by syssi** [comment]
The device support of the ZA5 is very basic right now. I will update the device support soon. I'm looking for testers.

**Comment by syssi** [comment]
Let's close this. Please subscribe #151.
