### ISSUE TITLE
Improve zhimi.fan.za5 support

### ISSUE THREAD

**Issue by Aliskin-Papa** [syssi/xiaomi_fan#151]
After adding zhimi.fan.za5 in the HA attribute this fan not show, but if i am add this fan from Xiaomi MIoT Integration, all attribute show.

In this integration:
![SmartSelect_20210628-202129_Home Assistant.jpg](https://user-images.githubusercontent.com/76951399/123689232-ab26c380-d85b-11eb-8f38-fdce016d1c02.jpg)

And with Xiaomi MIoT Integration:
![SmartSelect_20210628-213836_Home Assistant.jpg](https://user-images.githubusercontent.com/76951399/123689324-c85b9200-d85b-11eb-87a5-acd97aec8066.jpg)

**Comment by syssi** [comment]
The support of the ZA5 is very basic right now. I will improve the device support soon. The screenshots are helpful because of the example values per attribute.

**Comment by filikun** [comment]
@syssi Yeah there is a lot on ZA5 right now, maybe combine all those tickets to one. [Here's some from the same device ](https://github.com/syssi/xiaomi_fan/issues/147#issuecomment-869585670)

**Comment by syssi** [comment]
Sorry guys. There is a better issue to follow: #69

So much duplicates. I did lost the track. ;-)
