### ISSUE TITLE
Mi Smart Standing Fan Pro suppor?

### ISSUE THREAD

**Issue by Stooovie** [syssi/xiaomi_fan#157]
Hi, the Mi Smart Standing Fan Pro is not supported? Thanks!

**Comment by RPaulsson** [comment]
I also would like support for Mi Smart Standing Fan Pro.

**Comment by CorePoint** [comment]
I think it's just the dmaker.fan.p15.

**Comment by syssi** [comment]
Please use `miiocli` to ask your device about the exact model identifier. If it's a `dmaker.fan.p15` it's already supported.
