### ISSUE TITLE
Any way to get integration to create unique ID?

### ISSUE THREAD

**Issue by TDK2525** [syssi/xiaomi_fan#158]
Hi,

I am a big fan of this integration and I am currently using it to integrate to integrate two dmaker.fan.p18 fan's into my HA setup. I am however experiencing that I am not able to assign the two fans I have added via my configuration.yaml file to any "Areas" in my HA because HA is saying that they do not have a unique ID.

Is there any way to add this to the integration, or a workaround to manually set one? I have searched this issues list and Google and have not been able to see any ways of doing it.

**Comment by syssi** [comment]
If you don't set a model at your configuration a unique id is generated:

https://github.com/syssi/xiaomi_fan/blob/77c8d2a49bc8985db090de76506fdfaa06689d30/custom_components/xiaomi_miio_fan/fan.py#L345

**Comment by TDK2525** [comment]
Thanks @syssi - I just commented out the model in my configuration.yaml file and I was now able to assign the fan's to their respective rooms! Thank you so much for your pointer and for all your work with making the integration in the first place. I for one one really appreciate it as I am able to use my great Xiaomi fan's in HA because of you - THANKS!
