### ISSUE TITLE
Turn Left/Right doesn't work for dmaker.fan.p15 (Mi Smart Standing Fan Pro)

### ISSUE THREAD

**Issue by CorePoint** [syssi/xiaomi_fan#159]
I saw somebody opened the same [issue for a different model](https://github.com/syssi/xiaomi_fan/issues/88).
Although what I found weird  is that the custom card calls `fan.set_direction:` with `left` or `right`, but when I look it up under the HA's developer tools it has `forward` or `reverse`.
Anyway it doesn't work for me with either service call, although it works in the Xiaomi Home App.

Maybe I should also mention that the fan could be a different EU version or something, if I can do anything to help to identify any differences please tell me. Everything else seems to work though.

Thank you for your continued work!

**Comment by shlomki** [comment]
There's already an open issue for this where we've found the problem #139

**Comment by CorePoint** [comment]
@shlomki 
Thank you very much for letting me know! Don't know why I didn't find the issue in my search.
Seems like the fix should land in home assistant soon, because there was a release a week ago. :)
