### ISSUE TITLE
Model 3 Fan throwing back only 3 modes and another mode called off? 

### ISSUE THREAD

**Issue by semyag** [syssi/xiaomi_fan#166]
I can connect to my fan and control speed settings... kinda. I can change the speed up to 74% and it stops because it can only see three modes.  I will attach the pastebin for the error I am getting however an interesting thing, I purchased the V3 and in the python script to get the model I see  zhimi.fan.za5 instead. 

https://pastebin.com/25RHFqR4

Coffee if anyone can help me get this working!

**Comment by Kugelfang666** [comment]
I think the necessary changes have already been merged into the dev version bu @syssi did not jet put out a new release

**Comment by semyag** [comment]
Thanks for the update! Most likely ill just prime the S2 version, just to see if I can get that running sooner

**Comment by syssi** [comment]
@Kugelfang666 Thanks for the reminder. I will push a release now! :-)

**Comment by syssi** [comment]
Please update the component and give it a try!
