### ISSUE TITLE
 cannot import name 'SUPPORT_PRESET_MODE' from 'homeassistant.components.fan'

### ISSUE THREAD

**Issue by iwangzhuo** [syssi/xiaomi_fan#168]
Platform error fan.xiaomi_miio_fan - cannot import name 'SUPPORT_PRESET_MODE' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)

model:
Pedestal Fan Fan SA1 | zhimi.fan.sa1

how can I do?

**Comment by syssi** [comment]
Which HA core version do you use?

**Comment by iwangzhuo** [comment]
> Which HA core version do you use?

core_0.117.3

**Comment by syssi** [comment]
Please update your HA core version. This custom component isn't compatible with 0.117.3 anymore!

**Comment by iwangzhuo** [comment]
OK, I update in haas yesterday,But I found many Componnets fails, I restored use the backup then.
