### ISSUE TITLE
got zhimi.fan.za5 the integration list for sg / cn server doesn't show up

### ISSUE THREAD

**Issue by p2544** [syssi/xiaomi_fan#171]
I got xiaomi standing fan model zhimi-fan-za5
already install hacs reboot and add integration, adding as picture didn't find this model you mentioned that also support.

![image](https://user-images.githubusercontent.com/24413696/136122521-a0ccce18-74d1-4ac5-a9a3-e768e3f4dc47.png)

**Comment by syssi** [comment]
This custom component doesn't provide a integration card at the HA frontend. You have to extend your `configuration.yaml` and restart HA.

**Comment by syssi** [comment]
Correct!

**Comment by syssi** [comment]
The ZA5 support of this custom component is broken at the moment: https://github.com/syssi/xiaomi_fan/issues/176

**Comment by syssi** [comment]
Please give it another try (version `0.5.4`). The issue should be fixed now.
