### ISSUE TITLE
Xiaomi Fan stopped working after HA upgrade to 2021.12.x

### ISSUE THREAD

**Issue by purplephoenix76** [syssi/xiaomi_fan#176]
Hi, the custom component was working before i've upgrade HA to 2021.12.0. Observed this issue in both 12.0 & 12.1
Below is the trace from HA logger.

Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_fan/fan.py:1676
Integration: Fan (documentation, issues)
First occurred: 16:30:44 (1 occurrences)
Last logged: 16:30:44

Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 445, in async_setup_platform
    fan = FanZA5(host, token, model=model)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1676, in __init__
    self.model = model
AttributeError: can't set attribute

Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:153
First occurred: 16:30:44 (1 occurrences)
Last logged: 16:30:44

Found an unsupported model 'zhimi.fan.za5' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by majagu** [comment]
Same issue as PurplePhoenix76, starting after 2021.12.1 update.
Attempted reinstall via HACS and server restart; no improvement.

Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:153
First occurred: 5:43:41 PM (2 occurrences)
Last logged: 5:43:41 PM

Found an unsupported model 'zhimi.fan.za5' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

**Comment by pezmannen** [comment]
Stopped working for me aswell

**Comment by jonicunha** [comment]
Hi,
I'm having the same problem, zhimi.fan.za5 stopped working after HA update.
I'm using version 0.5.3 and HA 2021.12.2

Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_fan/fan.py:1676
Integration: Fan (documentation, issues)
First occurred: 12:44:13 PM (1 occurrences)
Last logged: 12:44:13 PM
Error while setting up xiaomi_miio_fan platform for fan

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 445, in async_setup_platform
    fan = FanZA5(host, token, model=model)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1676, in __init__
    self.model = model
AttributeError: can't set attribute

**Comment by tony42035** [comment]
Same issue here

**Comment by duchiepkt** [comment]
@syssi please fit it. thank you!

**Comment by gitenu** [comment]
Same issue here. Hope the maintainer can look into it after the holiday period.

**Comment by syssi** [comment]
I've an idea what's going on and will prepare a fix. If you cannot wait and you are an owner of the ZA5 you could try the official integration (`xiaomi_miio`). The device should be supported now. The official integration supports config flow and can be added by the "add integration" button.

**Comment by syssi** [comment]
Please give it another try (version `0.5.4`). The issue should be fixed now.
