### ISSUE TITLE
Add HA core 2022.3.0 compatibility

### ISSUE THREAD

**Issue by JuhaFIN1** [syssi/xiaomi_fan#179]
Hello!

I updated to new HA core core-2022.3.0 and this HACS integration disapheres. I see it under config/custom_components, but it dosent show up in HACS and hacs search wont find it even. And this dosent work, and when i try to reboot HA, it says: Platform error fan.xiaomi_miio_fan - No module named 'miio.fan'.

What to do?

**Comment by syssi** [comment]
This custom component needs to be updated to be compatible with the new HA core version

**Comment by robikop** [comment]
Same here.

**Comment by matteos1** [comment]
same here

**Comment by qiang221** [comment]
same here

**Comment by matteos1** [comment]
is it possible to integrate it via a graphical interface?
