### ISSUE TITLE
Add zhimi.fan.fa1 support 

### ISSUE THREAD

**Issue by rootsnet** [syssi/xiaomi_fan#186]
Can you please add this fan to this component to support?

Device Name: Xiaomi Mijia DC Frequency Conversion Circulation
Device Model: zhimi.fan.fa1
Model Number: ZLXHS01ZM
Miot Spec: https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:zhimi-fa1:1

Thank you.

**Comment by Aliskin-Papa** [comment]
One year...

**Comment by syssi** [comment]
Please be nice. What do you think how many devices does Xiaomi launch per year and how many people are involved?

**Comment by syssi** [comment]
Duplicate of #79.
