### ISSUE TITLE
Custom component bug fixed

### ISSUE THREAD

**Issue by apple4105** [syssi/xiaomi_fan#19]
Yesterday i found custom component cannot work normally with model fan.sa1.After you told that If the library complains about 17 requests properties the implementation of the zimi.fan.v3 / default is used,i tried to deal with the problem.Finally,i found the bug,that is a little mistake.In `miio.py`,models are use "zimi",but in `xiaomi_miio_fan.py` use "zhimi",so that made custom component cannot work.So,please update your code.Thank you for your contribution.

**Comment by syssi** [comment]
Wow! Gold catch!

**Comment by syssi** [comment]
Fixed! :-)
