### ISSUE TITLE
Need help installing the integration

### ISSUE THREAD

**Issue by cerbertof** [syssi/xiaomi_fan#206]
Hi,
I can't install this integration (I have already installed others with HACS though). In HACS everything seems ok, the integration appears as installed, I added the code in configuration.yaml with the correct ip and the correct token.
On the other hand, after restarting home assistant, I do not see the integration in the home assistant menu. I guess I missed a step but I can't see which one...
Can anyone help me ?

**Comment by syssi** [comment]
Please don't expect the custom component is popping up as tile at the integration or device page. Please go to the `developer tools`, open the `states` tab and search for a `fan` entity (f.e. `fan.xiaomi...`. The entitiy name depends on your yaml configuration name). If the IP address and the token are correct you should find a single `fan` entity.

**Comment by cerbertof** [comment]
> Please don't expect the custom component is popping up as tile at the integration or device page. Please go to the `developer tools`, open the `states` tab and search for a `fan` entity (f.e. `fan.xiaomi...`. The entitiy name depends on your yaml configuration name). If the IP address and the token are correct you should find a single `fan` entity.

Thanks, it's ok !
