### ISSUE TITLE
fan.set_direction not working for dmaker.fan.p39

### ISSUE THREAD

**Issue by ryan13mt** [syssi/xiaomi_fan#212]
Although dmaker.fan.p39 is not mentioned in the list of supported devices it seems to work with all the features apart from the set_direction. The device makes a beep when receiving this command but nothing else happens. 

This is the documentation of the device: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p39:1

**Comment by JoeTN** [comment]
I have the same fan. May I ask how your configuration.yaml looks like ?
If I try to configure mine like this, I see in the logs that it says "device not supported, please create issue", and then the fan doesn't show up in hass.

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi tower fan
    host: 192.168.10.67
    token: my-token-here

**Comment by syssi** [comment]
The device is supported now.
