### ISSUE TITLE
Unsupported device found dmaker.fan.p5c

### ISSUE THREAD

**Issue by xieahuiha** [syssi/xiaomi_fan#218]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 13:22:20 (1 occurrences)
Last logged: 13:22:20

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: dmaker.fan.p5c

**Comment by syssi** [comment]
Duplicate #224
