### ISSUE TITLE
Services to turn_on/off fan (or change fan speed) are missing in HAAOS

### ISSUE THREAD

**Issue by mbaluch** [syssi/xiaomi_fan#222]
Hi, 
I installed the integration and see only couple of services related to controlling the fan. Most importantly services to turn the fan ON/OFF are missing. 

**Environment:**
Xiaomi Mi Smart Pedestal Fan 2023.6.0.0
Home Assistant 2023.6.3
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest

**Fan model**
dmaker.fan.p18 /  dmaker.fan.p10

**Comment by syssi** [comment]
There should be generic services:

```
fan.turn_off
fan.turn_on
```

**Comment by mbaluch** [comment]
My bad. I completely missed these generic entities. Thank you for the pointer.

**Comment by mbaluch** [comment]
Please consider this resolved.
