### ISSUE TITLE
Add dmaker.fan.p39 (Tower Fan) support

### ISSUE THREAD

**Issue by paranerd** [syssi/xiaomi_fan#223]
Hi,

Just got my new Xiaomi Tower Fan (dmaker.fan.p39) but failed to control it via HA due to lack of support.
Is there any way someone could integrate that?

Much appreciated :-)!

**Comment by mbuchber** [comment]
I have exactly the same problem... please help!

**Comment by paranerd** [comment]
I actually ended up building it myself: https://github.com/syssi/xiaomi_fan/pull/225
Just waiting for approval 😃

**Comment by mbuchber** [comment]
Wow thanks a lot! Great work!

**Comment by paranerd** [comment]
Well, for now it only "Works on my machine" 😉 . Feel free to test!
