### ISSUE TITLE
Can not find integration in HACS

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [syssi/xiaomi_fan#227]
@syssi I can not find the integration in HACS if I search for "Xiaomi Mi Smart Pedestal Fan Integration" all I get is the "Xiaomi Mi Air Purifier & Xiaomi Mi Air Humidifier" integration.... any idea why this happens?

**Comment by Dud3z** [comment]
same here

**Comment by syssi** [comment]
Please search for "xiaomi_miio_fan". It's available.
