### ISSUE TITLE
XiaomiGenericDevice.async_turn_on() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by wokkeltje13** [syssi/xiaomi_fan#239]
Since HA 2023.12 I receive an error when turning on the fan. Turning off is working.
I receive the following log entry.

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:05:46 (6 occurrences)
Last logged: 11:39:33

[140603200636608] XiaomiGenericDevice.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
[140603187250112] XiaomiGenericDevice.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
[140602901802944] XiaomiGenericDevice.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 305, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: XiaomiGenericDevice.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
`

**Comment by ankitmehtame** [comment]
I have the same error, downgraded to 2023.11 (works fine with 2023.11)

**Comment by syssi** [comment]
I will prepare a 2023.12 compatible release as soon as possible.

**Comment by ostracizado** [comment]
For now simply change the automation or script to set fan: set speed X%; instead of fan: turn on.

**Comment by rothconsulting** [comment]
Had the same problem. 

Problem cause appears to be this:
https://github.com/home-assistant/core/commit/953a212dd697c5b916a335869bed8b36be466b92

In line 635 of fan.py an additional argument is required to make it work again.
```
#    async def async_turn_on(self, speed: str = None, **kwargs) -> None:
#    Fix for HA 2023.12.2 where turn_on would not work anymore.
    async def async_turn_on(self, speed: str = None, mode: str = None, **kwargs) -> None:
```

**Comment by wokkeltje13** [comment]
Tnx, this fix seems to work, when will this be released?

**Comment by syssi** [comment]
I will prepare a release soon.

**Comment by syssi** [comment]
I've prepared a new release. Please give it a try!

**Comment by wokkeltje13** [comment]
I see some errors and fan is unavailable now

Logger: miio.miioprotocol
Source: /usr/local/lib/python3.11/site-packages/miio/miioprotocol.py:240
First occurred: 20:00:13 (3 occurrences)
Last logged: 20:01:33

Got error when receiving: timed out

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:929
First occurred: 20:00:53 (2 occurrences)
Last logged: 20:01:23

Update of fan.ventilator_bureau is taking over 10 seconds

Logger: miio.miioprotocol
Source: /usr/local/lib/python3.11/site-packages/miio/miioprotocol.py:240
First occurred: 20:00:13 (3 occurrences)
Last logged: 20:01:33

Got error when receiving: timed out

**Comment by syssi** [comment]
Are you sure your fan isn't in deep sleep? Are you able to ping the device?

**Comment by wokkeltje13** [comment]
Sorry fan changed its IP because of some network maintenance today. Can be closed.

**Comment by NzKyle** [comment]
> I've prepared a new release. Please give it a try!

Looks to be working on my side now - thanks! 👍
