### ISSUE TITLE
fan.turn_on no longer working

### ISSUE THREAD

**Issue by tsmanz** [syssi/xiaomi_fan#240]
I have 3 Xiaomi 2S fans that were working perfectly. Recently I noticed calling the fan.turn_on service fails with unknown error. When trying to turn on the entity I get the following error.

XiaomiGenericDevice.async_turn_on() takes from 1 to 2 positional arguments but 3 were given

I run HassOS with all updates as well as the latest HACS update for this integration.

**Comment by NzKyle** [comment]
See #239

**Comment by syssi** [comment]
Please update the custom component to version 2023.12.0.0. The issue is fixed here.
