### ISSUE TITLE
Deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by heinemannj** [syssi/xiaomi_fan#243]
`Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

`Entity None (<class 'custom_components.xiaomi_miio_fan.fan.XiaomiFan1C'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.SET_SPEED|OSCILLATE|PRESET_MODE: 11>, please create a bug report at https://github.com/syssi/xiaomi_fan/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

**Comment by askthomas** [comment]
SUPPORT_OSCILLATE was used from xiaomi_miio_fan, this is a deprecated constant which will be removed in HA Core 2025.1
SUPPORT_PRESET_MODE was used from xiaomi_miio_fan, this is a deprecated constant which will be removed in HA Core 2025.1
SUPPORT_SET_SPEED was used from xiaomi_miio_fan, this is a deprecated constant which will be removed in HA Core 2025.1
SUPPORT_DIRECTION was used from xiaomi_miio_fan, this is a deprecated constant which will be removed in HA Core 2025.1
SUPPORT_OSCILLATE was used from xiaomi_miio_fan, this is a deprecated constant which will be removed in HA Core 2025.1
SUPPORT_PRESET_MODE was used from xiaomi_miio_fan, this is a deprecated constant which will be removed in HA Core 2025.1
SUPPORT_SET_SPEED was used from xiaomi_miio_fan, this is a deprecated constant which will be removed in HA Core 2025.1
SUPPORT_DIRECTION was used from xiaomi_miio_airpurifier, this is a deprecated constant which will be removed in HA Core 2025.1.

**Comment by snp88** [comment]
> This should work: #245

Your fix work for me ;) thx

**Comment by syssi** [comment]
Fixed by https://github.com/syssi/xiaomi_fan/commit/2b025ac6a884b3f5d88c2f49e49116ee55165d78. Kudos to @override80
