### ISSUE TITLE
Please add support xiaomi smart tower fan 2 to Home assistant (dmaker.fan.p45)

### ISSUE THREAD

**Issue by akrush24** [syssi/xiaomi_fan#249]
I would like to request support for the dmaker.fan.p45 model.

```2024-05-02 23:55:35.166 ERROR (MainThread) [custom_components.xiaomi_miio_fan.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p45```

**Comment by Sungurik** [comment]
+1

**Comment by unegade** [comment]
+1

**Comment by sanyafifa** [comment]
+1

**Comment by igzvaric** [comment]
+1

**Comment by syssi** [comment]
This is a duplicate of #214.

**Comment by vismuthxx** [comment]
+1

**Comment by vismuthxx** [comment]
The fan has not been added like this since 2025.

**Comment by gokhanhotan** [comment]
+1
