### ISSUE TITLE
Xiaomi Smart Standing fan 2 Pro, model: dmaker.fan.p33 .  

### ISSUE THREAD

**Issue by Rafas20** [syssi/xiaomi_fan#259]
I tried to integrate my new fan to HA but it does not show any controls for the fan.. Did i made anything wrong? Could you help me please? As a solution i thought to try downgrade the firmware of the fan but thats not easy and safe task (for me at least)
![image](https://github.com/syssi/xiaomi_fan/assets/143114577/6e894102-84b8-46c0-9608-624c800cb74c)
![image](https://github.com/syssi/xiaomi_fan/assets/143114577/e3769b50-f3c4-45b8-9703-345337e2f74e)

**Comment by Rijnme** [comment]
I am struggling with the same issue. So I will follow this issue

**Comment by syssi** [comment]
Please go to the `Entities` tab and search for a `fan` entity. Do you find something here? This integration was developed long time ago. The concept of a `device` did not yet exist at that time.

**Comment by lug-gh** [comment]
PS: I use the p33 Fan in the official HA Xiaomi Extension without any problems.
It shows the device is unkown, but just select p11 Fan then, they have the same functions.

**Comment by Rafas20** [comment]
Its ok i found that entity.. Thank you.. I hope this project help others to..

**Comment by Rafas20** [comment]
Hi  for some reason entity became unavailable and i deleted it. Then i follow the same procedure to install the fan again through HACS as device and now i cannot find that fan entity again.. Whats going on? Will i be able to find that entity again?
