### ISSUE TITLE
How to set natural_mode

### ISSUE THREAD

**Issue by radokristof** [syssi/xiaomi_fan#262]
Dear all,

How can I use the service `xiaomi_miio_fan.fan_set_natural_mode_on` or any other services for this integration?
I understand that correctly, that I need to create custom automation and buttons for it to work?

**Comment by syssi** [comment]
That's correct if you want to add a button to your dashboard. If you want to call the service once you could call the service using the developer tools at `http://<yourhost>/developer-tools/service`.
