### ISSUE TITLE
Natural Mode Option

### ISSUE THREAD

**Issue by 0xSamsara** [syssi/xiaomi_fan#264]
Hi @syssi, 

Is there an option to add a button for the natural mode? 

Currently if you create a card it only shows the options for:
- preset mode
- direction
- oscillating

![Screenshot 2024-07-23 at 10 44 49](https://github.com/user-attachments/assets/0af270b5-efb3-4c2e-a5bf-a727cae568a5)

I understand it would be possible to create a dedicated button for this, but would love to have it implemented in the standard card.

**Comment by syssi** [comment]
This requires a complete overhaul of this integration. My spare time doesn't allow this at the moment.

**Comment by 0xSamsara** [comment]
Hi @syssi, thanks for your quick response! Understood, then I'll fix it with a dedicated button. Thanks for all your work on this integration!
