### ISSUE TITLE
dmaker.fan.1c problem

### ISSUE THREAD

**Issue by Sygnus83** [syssi/xiaomi_fan#265]
Hi !
Supported device list : Pedestal Fan Fan 1C - dmaker.fan.1c

I have : Mi Smart Standing Fan 2 Lite / dmaker.fan.1c / jllds01dm  and its not working good.

This fan have 1-2-3 speed , the card show only 2- 4 speed .

No natural mode, set delay off mode and angle service cant find, so i think need hide this buttons if its possible.

**Comment by syssi** [comment]
Are you sure this is an issue of this integration or the custom lovelace card you are using which is not part of this project.
