### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [syssi/xiaomi_fan#27]
Hello! I'd like to create a logo for your project, since I read everything about it and I already got an idea, just let me know if you'd want me to start designing it :)

**Comment by syssi** [comment]
Feel free to provide a PR!

**Comment by newfinal100** [comment]
![color variations-01](https://user-images.githubusercontent.com/49202520/55632687-11c2f100-57bb-11e9-9567-63cc791d9def.jpg)
![color variations 2-01](https://user-images.githubusercontent.com/49202520/55632696-1687a500-57bb-11e9-9e55-bdb2e1a9780d.jpg)

Here are a few variations, let me know what you think!

**Comment by syssi** [comment]
I would be happy about some Home Assistant context because this is a custom component for Home Assistant.

**Comment by newfinal100** [comment]
![Untitled-1-01](https://user-images.githubusercontent.com/49202520/55635206-72086180-57c0-11e9-8354-1df93efc4d88.jpg)

How about this?

**Comment by newfinal100** [comment]
The idea behind it is to give visual representation of the words Smart (the light bulb) + Fan (the fan shape) + Home (the home shape)

**Comment by newfinal100** [comment]
![extra version-01](https://user-images.githubusercontent.com/49202520/55636341-f22fc680-57c2-11e9-976a-0726542c48ec.jpg)

Here is one more version :)
