### ISSUE TITLE
[Bug:] Natural Mode Switch only turns it on

### ISSUE THREAD

**Issue by ffuuuuu** [syssi/xiaomi_fan#270]
On the widget taping natural mode turns it on. But tapping it again doesn't turn it off.

I tested manually calling the service:

xiaomi_miio_fan.fan_set_natural_mode_off

This works exactly as it should but on the fan card it doesn't switch back off, just turns it on.

This was tested with two Xiaomi Standing Fans 2S.

This is one of the entities (natural is off here):
preset_modes:
  - "off"
  - Level 1
  - Level 2
  - Level 3
  - Level 4
direction: null
oscillating: false
percentage: 100
percentage_step: 1
preset_mode: Level 4
model: zhimi.fan.za4
angle: 120
raw_speed: 0
delay_off_countdown: 0
ac_power: true
oscillate: false
direct_speed: 100
natural_speed: 0
child_lock: false
buzzer: false
led_brightness: 1
use_time: 9010
temperature: null
humidity: null
battery: null
battery_charge: null
button_pressed: null
led: null
battery_state: null
friendly_name: Fan_1
supported_features: 15

**Comment by syssi** [comment]
Which widget you are talking about? This is project is just an integration which exposes the fan entity and some services. May be this isn't the correct place for your issue?

**Comment by ffuuuuu** [comment]
> Which widget you are talking about? This is project is just an integration which exposes the fan entity and some services. May be this isn't the correct place for your issue?

Talking about the custom:fan-xiaomi card. Isn't this part of the integration?

**Comment by ffuuuuu** [comment]
Wrong github. Sorry!
