### ISSUE TITLE
Does update 2024.8.0 not works with HA 2024.7.4?

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [syssi/xiaomi_fan#272]
As the description says I updated to 2024.8.0 and then the integration not starts and my xiaomi fans show as unavailable, when i rollback to 2024.7.0 then all works again as expected. I am still on HA version 2024.7.4

**Comment by syssi** [comment]
Interesting. I will have a look. Do you see anything at the logs?

**Comment by smarthomefamilyverrips** [comment]
> Interesting. I will have a look. Do you see anything at the logs?

@syssi just message that fan was not available from what I remember, I already did go back to 2024.7.0 so not have logs available anymore, sorry



> Do you use this custom component or the official HA core component?

Yes I do use this custom component, the core one not fully supports my fans

**Comment by syssi** [comment]
This is correct. Release 2024.8.0.0 requires Home Assistant Core 2024.8.0. Your version isn't compatible.

**Comment by smarthomefamilyverrips** [comment]
> This is correct. Release 2024.8.0.0 requires Home Assistant Core 2024.8.0. Your version isn't compatible.

@syssi OK then will update on a later time after did update to HA 2024.8.X or later
