### ISSUE TITLE
Xiaomi Smart Standing fan 2 Pro, model: dmaker.fan.p33 ---2

### ISSUE THREAD

**Issue by Rafas20** [syssi/xiaomi_fan#279]
Hi  for some reason entity became unavailable and i deleted it. Then i follow the same procedure to install the fan again through HACS as device and now i cannot find that fan entity again.. Whats going on? Will i be able to find that entity again?

![image](https://github.com/user-attachments/assets/41131553-3c75-47dd-b6fc-127260405e05)
![image](https://github.com/user-attachments/assets/b41ad4df-0654-4ad9-a87f-fc6b2d517651)

_Originally posted by @Rafas20 in https://github.com/syssi/xiaomi_fan/issues/259#issuecomment-2332326124_

**Comment by Rafas20** [comment]
Its okay i installed recent update of home assistant and i got this xiaomi fan control entity again. It was the home assistant that was needed an update. Now it works fine again

**Comment by Tuatop** [comment]
> Its okay i installed recent update of home assistant and i got this xiaomi fan control entity again. It was the home assistant that was needed an update. Now it works fine again

Confirmed. After update HA version to 2024.9, this integration back to work again.

ps. dmaker.fan.p18 also works with this solution.
