### ISSUE TITLE
Support device model dmaker.fan.p5

### ISSUE THREAD

**Issue by 1043717432** [syssi/xiaomi_fan#30]
Support device model dmaker.fan.p5

Hi, today I received my "xiaomi SmartmiFan 1x" 
Sadly it is not yet recognised by your component. Could you please integrate it?

I try to give the same information which you required in similar requests, let me know if you need more information:
Mi Home App doesn't seem to display battery stats

Support device model dmaker.fan.p5

bash-4.4# mirobo --ip 192.168.120.157 --token df0xx25caxxcedxx7656368xx79aaxx9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[True, 'nature', 35, True, 140, 0, True, False, False, 2]

**Comment by StanislavBolshakov** [comment]
Came across the same issue. Component returns an error on load:

```
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p5
```

**Comment by vandijks** [comment]
I can help testing if required, received the same device today (2019, 1X, 140deg instead of 120, wired).

**Comment by syssi** [comment]
Could somebody provide the output of:

```
for PROP in ac_power angle angle_enable bat_charge bat_state battery button_pressed buzzer child_lock humidity led led_b natural_level power poweroff_time speed speed_level temp_dec use_time
do
  mirobo --ip IP --token TOKEN raw-command get_prop "['$PROP']"
done
```

and

```
for PROP in power mode speed roll_enable roll_angle time_off light beep_sound child_lock
do
  mirobo --ip IP --token TOKEN raw-command get_prop "['$PROP']"
done
```

I will implement the device support as soon as the output is known.

**Comment by 1043717432** [comment]
稍等，我现在立马测试！

**Comment by syssi** [comment]
Cool! Thanks.

**Comment by StanislavBolshakov** [comment]
```Sending cmd get_prop with params ['ac_power']
[True]
Sending cmd get_prop with params ['angle']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['angle_enable']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['bat_charge']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['bat_state']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['battery']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['button_pressed']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['buzzer']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['child_lock']
[False]
Sending cmd get_prop with params ['humidity']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['led']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['led_b']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['natural_level']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['power']
[True]
Sending cmd get_prop with params ['poweroff_time']
[True]
Sending cmd get_prop with params ['speed']
[35]
Sending cmd get_prop with params ['speed_level']
[35]
Sending cmd get_prop with params ['temp_dec']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]
Sending cmd get_prop with params ['use_time']
[True, 'normal', 35, False, 140, 0, True, False, False, 2]```

**Comment by 1043717432** [comment]
@syssi  
`/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[True, 'nature', 100, False, 140, 0, True, False, False, 4]
/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[False, 'nature', 100, False, 140, 0, True, False, False, 4]
/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[False, 'nature', 100, False, 140, 0, True, False, False, 4]
/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[True, 'nature', 100, False, 140, 0, True, False, False, 4]
/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[True, 'nature', 1, False, 140, 0, True, False, False, 1]
/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[True, 'nature', 35, False, 140, 0, True, False, False, 2]
/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['$PROP']"
Sending cmd get_prop with params ['']
[True, 'nature', 70, False, 140, 0, True, False, False, 3]
/config #`

**Comment by syssi** [comment]
@StanislavBolshakov If you request a list of properties do you retrieve a proper response:

```


mirobo --ip IP --token TOKEN raw-command get_prop "['power','mode','speed','roll_enable','roll_angle','time_off','light','beep_sound','child_lock']"
```

**Comment by 1043717432** [comment]
`/config # mirobo --ip 192.168.120.129 --token df02225caf5cedxxxx563687e79aadd9 raw-command get_prop "['power','mode','speed','roll_enable','roll_angle','time_off','light','beep_sound','child_lock']"
Sending cmd get_prop with params ['power', 'mode', 'speed', 'roll_enable', 'roll_angle', 'time_off', 'light', 'beep_sound', 'child_lock']
[True, 'nature', 70, False, 140, 0, True, False, False]`

**Comment by 1043717432** [comment]
我按一次风速和转动方向 ，都只是这样的反馈！

**Comment by 1043717432** [comment]
抱歉不会编辑回复，可能你看得有点乱！

**Comment by StanislavBolshakov** [comment]
@syssi yup.
```
Sending cmd get_prop with params ['power', 'mode', 'speed', 'roll_enable', 'roll_angle', 'time_off', 'light', 'beep_sound', 'child_lock']
[False, 'normal', 35, False, 140, 0, True, False, False]
```
But I believe there should be led brightness as well. It's listed with 0,1,2 depending on LED state. 

```
Sending cmd get_prop with params ['']
[False, 'normal', 35, False, 140, 0, True, False, False, 2]
```

**Comment by syssi** [comment]
I want to request a list of properties because of future firmware updates. If the response of the empty request changes the values are mapped incorrect.

**Comment by syssi** [comment]
Could somebody provide a list of the different available "mode"s?

**Comment by 1043717432** [comment]
How to provide a list of different modes?

**Comment by StanislavBolshakov** [comment]
> Could somebody provide a list of the different available "mode"s?

It's either normal or nature.

**Comment by syssi** [comment]
The maximum speed is 100%?

**Comment by StanislavBolshakov** [comment]
> The maximum speed is 100%?

Yes

**Comment by syssi** [comment]
This is the first step (extending python-miio): https://github.com/rytilahti/python-miio/pull/513

@StanislavBolshakov Do you like to install and test the feature branch?

```
$ pip3 install https://github.com/syssi/python-miio/archive/feature/dmaker-fan-p5-support.zip
[...]
$ miiocli fanp5
Usage: miiocli fanp5 [OPTIONS] COMMAND [ARGS]...

Options:
  --ip TEXT     [required]
  --token TEXT  [required]
  --help        Show this message and exit.

Commands:
  delay_off       Set delay off seconds.
  info            Get miIO protocol information from the device.
  off             Power off.
  on              Power on.
  raw_command     Send a raw command to the device.
  set_angle       Set the oscillation angle.
  set_buzzer      Set buzzer on/off.
  set_child_lock  Set child lock on/off.
  set_led         Turn led on/off.
  set_mode        Set mode.
  set_oscillate   Set oscillate on/off.
  set_speed       Set speed.
  status          Retrieve properties

```

**Comment by StanislavBolshakov** [comment]
Getting an error:

```
bash-4.4#  miiocli fanp5
Usage: miiocli [OPTIONS] COMMAND [ARGS]...
Try "miiocli --help" for help.

Error: No such command "fanp5".
```

**Comment by syssi** [comment]
In this case you have python-miio installed two times now. This should work:

```
~/.local/bin/miiocli fanp5
```

**Comment by StanislavBolshakov** [comment]
Missed the --upgrade key, sorry. 

Works fine:

- Info provides accurate info about device, firmware and WLAN. 
- On/off toggles the device.
- Buzzer 
- Child mode
- LED
- On/off oscillating
- Speed
- Setting mode normal & nature

There is space for improvement: 
- Delay_off expects minutes, not seconds. Overwise works.
- Set_angle should receive [30,60,90,120,140], other values won't work. Will it make sense to call set_oscillate prior set_angle if oscillating currently disabled?

**Comment by syssi** [comment]
1. Fixed.
2. What happens if you turn off oscillation, set_angle 90 and retrieve the `status` afterwards. Does the property change and is the oscillation still disabled? I will restrict the accepted values.
3. Could you test `m_roll` as raw_command?

```
miiocli fanp5 --ip IP --token TOKEN raw_command m_roll "['left']"
...multiple times...
miiocli fanp5 --ip IP --token TOKEN raw_command m_roll "['right']"
...multiple times...
```

I'm unsure about "left" and "right". The proper payload is unknown up to now.

**Comment by StanislavBolshakov** [comment]
2. Value sets to 90.  Oscillation still being disabled.
3. Works fine.

**Comment by syssi** [comment]
Cool. In this case the implementation should be feature complete now:

https://github.com/rytilahti/python-miio/pull/513/commits/0f76c506606eaa60cf2445faf0f1f9b372a6ad55

Could you test the new command? 

```
$ pip3 install https://github.com/syssi/python-miio/archive/feature/dmaker-fan-p5-support.zip -U
[...]
miiocli fanp5 --ip IP --token TOKEN set_rotate left
miiocli fanp5 --ip IP --token TOKEN set_rotate right
```

**Comment by StanislavBolshakov** [comment]
It works!

**Comment by jiafengwang** [comment]
It works with python-miio, thx a lot!
Could you pls update the component for home-assistant
Thank you ver much!

**Comment by syssi** [comment]
A release of python-miio is needed first. Afterwards I will extend the HA component.

**Comment by yeyeyaya** [comment]
how to fix it?
2019-06-12 22:54:25 INFO (MainThread) [homeassistant.components.fan] Setting up fan.xiaomi_miio
2019-06-12 22:54:25 INFO (MainThread) [homeassistant.components.switch] Setting up switch.broadlink
2019-06-12 22:54:26 INFO (MainThread) [homeassistant.components.xiaomi_miio.fan] Initializing with host 192.168.3.10 (token 09d62...)
2019-06-12 22:54:26 INFO (MainThread) [homeassistant.components.xiaomi_miio.fan] dmaker.fan.p5 1.3.6 ESP8266 detected
2019-06-12 22:54:26 ERROR (MainThread) [homeassistant.components.xiaomi_miio.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p5

**Comment by syssi** [comment]
You have to wait. I will extend the component soon.

**Comment by yeyeyaya** [comment]
> You have to wait. I will extend the component soon.

thanks for  reply！

**Comment by huyoupe** [comment]
when will the HA component be extended

**Comment by yishangfei** [comment]
waiting

**Comment by syssi** [comment]
I won't make an estimate/promise here.

**Comment by creatorMao** [comment]
hi,  i seem to meet the problem too.  i bought the fan named 1x.

**Comment by wzpan** [comment]
+1. Same problem on mi fan 1X.

**Comment by bg9ega** [comment]
Same problem on dmaker.fan.p5,waiting....

**Comment by bieniu** [comment]
Any news about add support for dmaker.fan.p5?

**Comment by jiafengwang** [comment]
https://bbs.hassbian.com/thread-7645-1-1.html

**Comment by jiafengwang** [comment]
> Any news about add support for dmaker.fan.p5?

For temporary use

**Comment by jiafengwang** [comment]
https://bbs.hassbian.com/thread-7645-1-1.html

**Comment by bieniu** [comment]
I did yesterday a working version of the component for dmaker.fan.p5. It required the development version of the miio library.
https://github.com/bieniu/xiaomi_fan

**Comment by RPWO** [comment]
> A release of python-miio is needed first. Afterwards I will extend the HA component.

I think it was updated since, not sure if it includes everything you need

**Comment by RPWO** [comment]
Cool

**Comment by sjtuross** [comment]
I notice python-miio 0.4.6 has been released. What needs to be done to have this component work for dmaker.fan.p5?

**Comment by syssi** [comment]
I've update the custom component please give it a try!

**Comment by sjtuross** [comment]
`2019-10-10 17:08:44 ERROR (MainThread) [homeassistant.components.fan] xiaomi_miio_fan: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 439, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 425, in async_update
    self._oscillate = state.oscillate
  File "/usr/local/lib/python3.7/site-packages/miio/fan.py", line 174, in oscillate
    return self.data["angle_enable"] == "on"
KeyError: 'angle_enable'`

**Comment by surpasstop** [comment]
What is the error below?

ERROR (MainThread) [custom_components.xiaomi_miio_fan.fan] Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}

**Comment by syssi** [comment]
@sjtuross Please update the custom component again. We need a few iterations may be. I've improved the implementation. If the component doesn't crash anymore we should check all features are working fine.

**Comment by syssi** [comment]
@surpasstop Please update the custom component, too.

**Comment by surpasstop** [comment]
@syssi I've updated component and restart ha, another error occured
I use RPi3 b+ Raspian and docker based HA

Error while setting up platform xiaomi_miio_fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 231, in async_setup_platform
    from miio import FanP5
ImportError: cannot import name 'FanP5' from 'miio' (/usr/local/lib/python3.7/site-packages/miio/__init__.py)

**Comment by syssi** [comment]
In this case you don't have python-miio 0.4.6 installed. Please use the development version of HA.

**Comment by syssi** [comment]
Could you provide the xiaomi_miio_fan section of your `configuration.yaml`? This part shouldn't be used if you've the most recent version of the custom component. Relevent lines for the P5 are L572-L678.

**Comment by surpasstop** [comment]
Thank you syssi
I use two v3 and two p5 fan
V3 works fine well even after updating components

- platform: xiaomi_miio_fan
  name: ecroom fan
  host: 192.168.0.117
  token: 1a84028de6a8aa0c474fc5362140b440
  model: 'dmaker.fan.p5'
- platform: xiaomi_miio_fan
  name: ejroom fan
  host: 192.168.0.118
  token: 13915911513b46931b1ca035cf3edafe
  model: 'dmaker.fan.p5'

**Comment by syssi** [comment]
Could you remove the V3 temporary from your configuration? Just use:

```
fan:
  - platform: xiaomi_miio_fan
    name: ejroom fan
    host: 192.168.0.118
    token: 13915911513b46931b1ca035cf3edafe

# And enable the debug out / change the configuration of your "logger:" by

logger:
  default: warn
  logs:
    custom_components.fan.xiaomi_miio_fan: debug
    miio: debug
```

Restart HA and provide the error of the log. :-)

**Comment by surpasstop** [comment]
Here you are

2019-10-12 00:05:16 DEBUG (MainThread) [miio.device] 192.168.0.118:54321 (ts: 1970-02-06 05:30:57, id: 1) << {'id': 1, 'result': {'life': 3130257, 'uid': 1678397415, 'model': 'dmaker.fan.p5', 'token': '13915911513b46931b1ca035cf3edafe', 'fw_ver': '2.0.4', 'mcu_fw_ver': '0008', 'miio_ver': '0.0.6', 'hw_ver': 'esp8266', 'mmfree': 25056, 'mac': '40:31:3C:DC:74:2C', 'wifi_fw_ver': '2709610', 'ap': {'ssid': 'IoT_Home', 'bssid': '8A:36:6C:5A:12:47', 'rssi': -65, 'primary': 3}, 'netif': {'localIp': '192.168.0.118', 'mask': '255.255.255.0', 'gw': '192.168.0.1'}}}

2019-10-12 00:05:19 ERROR (MainThread) [homeassistant.components.fan] xiaomi_miio_fan: Error on device update!


  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 445, in async_update


AttributeError: 'FanStatusP5' object has no attribute 'natural_speed

**Comment by syssi** [comment]
My fault! Line 234 must be `XiaomiFanP5` instead `XiaomiFan`. I will fix it ASAP.

**Comment by surpasstop** [comment]
I've change that you mentioned, and restore my setting, reboot
Then.. Error occured

xiaomi_miio_fan: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 616, in async_update
    if state.direct_speed in range:
AttributeError: 'FanStatusP5' object has no attribute 'direct_speed'

**Comment by syssi** [comment]
Fixed. Thanks for your time! :-)

**Comment by surpasstop** [comment]
All is working well. Thanks syssi!!

**Comment by syssi** [comment]
Could provide some more testing/infos.

1. I want to know the different speed values (min/max) of the P5. If you use the mi home app, how much different speed values can you choose from?

**Comment by syssi** [comment]
You can add the second fan to the configuration again. Make sure to set the correct model or leave out the model parameter.

**Comment by surpasstop** [comment]
min/max speed value is 1~100
Second fan was added and P5 fan works fine now.

But V3 fan does not show speed level,
Is it correct [ATTR_SPEED] at line 421, 459 ?
[ATTR_SPEED_LEVEL] shows speed level..

**Comment by syssi** [comment]
The V3 has speed levels between 1 and 4. Should the P5 have the same speed levels? I will take a look at the speed levels of the V3.

**Comment by surpasstop** [comment]
P5 level is 1 ~ 4 too
Level 1 : 1
Level 2 : 35
Level 3 : 70
Level 4 : 100

**Comment by syssi** [comment]
I've added your values: https://github.com/syssi/xiaomi_fan/commit/6901cce4def0365e043593bc7d01d6912bb01156

And I've tried to fix the other fan level issues. Please give it a try!

**Comment by syssi** [comment]
Side note: I will remove the sped levels (1-4) in future because HA supports "off", "low", "medium" and "high" only **to be Google Home / Alexa comaptible**. As soon as we use other values for the speed level the devices cannot be controlled via Alexa.

**Comment by syssi** [comment]
Could you check both fans with the latest version of the component to make sure everything works fine now? Thanks in advance!

**Comment by surpasstop** [comment]
I'm sorry for late response
I applied your last code, all functions work fine,
except that I can't find attribute direct_speed at P5.
So I added ATTR_RAW_SPEED: "speed" below AVAILABLE_ATTRIBUTES_FAN_P5 = {
It works, thank you

**Comment by biscuitee** [comment]
hi, can the expert help to how to add newer xiaomi fan model into miio_fan? I have new model dmaker.fan.p9 and would like to control it via miio_fan . thanks in advanced

**Comment by syssi** [comment]
Device support was added some time ago.

**Comment by biscuitee** [comment]
Hi, I couldn't load the dmaker.fan.p9 using the latest xiaomi_miio_fan custom component.  My HA reported the following error:

     Invalid config for [fan.xiaomi_miio_fan]: value is not allowed for dictionary value @ data['model']. Got 'dmaker.fan.p9'. (See ?, line ?).

**Comment by syssi** [comment]
This issue is about the dmaker.fan.p5 (a miio device). You are asking about a dmaker.fan.p9 (a miot device) which isn't supported right now.

**Comment by fineemb** [comment]
Can your speed values ( raw speed, direct speed, natural speed )be obtained normally?

![01](https://user-images.githubusercontent.com/16739914/92317770-15ede080-f037-11ea-96ca-5f2107a3a9c9.jpg)
