### ISSUE TITLE
Add zhimi.fan.za3 support

### ISSUE THREAD

**Issue by brucey531** [syssi/xiaomi_fan#31]
Does this custom component work with the new custom_updater?

I can't get to work? I recently purchased the new SmartMi fan and this doesn't appear to work? 

not sure if its the fan thats not supported of the new customer updater?

can anyone let me know? Driving me mad

thanks

Josh

**Comment by syssi** [comment]
Which hardware model of the device do you own? The custom component updater isn't supported right now.

**Comment by brucey531** [comment]
Hi there. I have this model

https://banggood.app.link/8c1WE4nt2W

So to confirm? This custom compenent doesn't work with the new customer component updater at the moment?

Can you confirm if there is a way to get it working?

Thanks

**Comment by syssi** [comment]
The updater isn't needed to use this component. Do you have access to a linux system? Are you able to install `pip3 install python-miio` and test some commands?

**Comment by brucey531** [comment]
Unfortunately I'm ready my HA on socket on a Synology NAS.

**Comment by syssi** [comment]
Do you have access to an linux host just for testing? This model isn't supported right now.

**Comment by brucey531** [comment]
Sorry I don't. Thanks for replying though

**Comment by syssi** [comment]
In this case you have to wait. Sorry. :-)

**Comment by syssi** [comment]
@brucey531 If you take a look at your router/internet gateway/dhcp server. Could you provide the hostname of your fan? It should contain the model name of the device.

**Comment by syssi** [comment]
@StanislavBolshakov Could you compare this device (ZLBPLDS03ZM) with your dmaker.fan.p5? If it's the same this issue is a duplicate.

**Comment by StanislavBolshakov** [comment]
@syssi I'm afraid this is another device. The 1X fan has part number BPLDSM01DM

**Comment by rezmus** [comment]
it can be zhimi.fan.za3

**Comment by syssi** [comment]
@brucey531 I've updated the custom component. Please copy the component to your custom_components folder and give it a try!

**Comment by brucey531** [comment]
Many thanks

I'm just away on holiday so will try it as soon as I'm back at the end of the week

________________________________

**Comment by brucey531** [comment]
Hello

The name of my fan is zhimi-fan-za1_mibt16BC

I tried the new custom component and still doesn't appear to work. I'm pretty sure I have the right token. 

Thanks, Josh

**Comment by flishqq** [comment]
> Hello
> 
> The name of my fan is zhimi-fan-za1_mibt16BC
> 
> I tried the new custom component and still doesn't appear to work. I'm pretty sure I have the right token.
> 
> Thanks, Josh

Hello，如果你是使用智米风扇2无电池版的话我试过了最新版本，已经可以正确识别了
