### ISSUE TITLE
 zhimi.fan.za3

### ISSUE THREAD

**Issue by flishqq** [syssi/xiaomi_fan#34]
I updated the latest version and found that I have identified my fan( zhimi.fan.za3).
However, there are a few parameters that can be modified and can only change wind speed. Is this normal?

![img](https://s2.ax1x.com/2019/06/09/Vr15Wt.jpg)

**Comment by syssi** [comment]
Did you try the different services?

**Comment by syssi** [comment]
Duplicate #35. I will provide some instructions there.
