### ISSUE TITLE
need more attributes for Smartmi fan 2s (2019) (model: zhimi.fan.za4)

### ISSUE THREAD

**Issue by GameOver107** [syssi/xiaomi_fan#36]
@syssi: Thank you very much for your "xiaomi_fan" custom component.
My new smartmi fan 2s (2019) (model: za4) has been integrated successfully to hassio 0.92.
` "speed": 0,
  "speed_list": [
    "off",
    "Level 1",
    "Level 2",
    "Level 3",
    "Level 4"
  ],
  "oscillating": true,
  "model": "zhimi.fan.za4",
  "speed_level": "Level 1",
  "angle": 90,
  "delay_off_countdown": 0,
  "ac_power": true,
  "oscillate": true,
  "direct_speed": 1,
  "natural_speed": 1,
  "child_lock": false,
  "buzzer": true,
  "led_brightness": 1,
  "use_time": 530,
  "temperature": null,
  "humidity": null,
  "battery": null,
  "battery_charge": null,
  "button_pressed": null,
  "led": null,
  "battery_state": null,
  "friendly_name": "master fan",
  "supported_features": 7`
But if possible, please modify the component for its "battery", which shows level of battery. So that I can check when I shoud charge my fan suitably.
Now it only shows  <"battery": null>

Thanks alot

**Comment by IDmedia** [comment]
I have the same fan.
data:{"models":"zhimi.fan.za4","device":"crownlte"}

Did you have to change anything in order to get it to work? I'm just getting "Platform xiaomi_miio_fan not ready yet. Retrying in 180 seconds."

**Comment by michalterbert** [comment]
I have also zhimi.fan.za4 and it works:
![image](https://user-images.githubusercontent.com/15417117/61595367-813bdf80-abf6-11e9-9f48-1046b7bfa001.png)

But I would like to have battery status :)
Thanks!

**Comment by IDmedia** [comment]
> I have also zhimi.fan.za4 and it works:
> ![image](https://user-images.githubusercontent.com/15417117/61595367-813bdf80-abf6-11e9-9f48-1046b7bfa001.png)
> 
> But I would like to have battery status :)
> Thanks!

How did you obtain the token? I think I may have the wrong one, but no matter what I do, after deleting the logs on my Android phone the token is not added again. Not even Miio finds anything, but it works nicely in the Xiaomi app.

**Comment by michalterbert** [comment]
@IDmedia I used Xiaomi SmartHome app 5.4.49 for Android (debug logs enabled).

**Comment by IDmedia** [comment]
I'm on 5.5.43. Do I have to enable debug logs anywhere?

**Comment by Anisse4** [comment]
Hi guys,

I have also a model z4a but still error "Platform xiaomi_miio_fan not ready yet. Retrying in 180 seconds." I have retrieved the token from log file with mi home app 5.4.54, I have added the proper section in configuration.yaml

fan:
  - platform: xiaomi_miio
    host: 192.168.1.43
    token: 4e990266227xxxxxxxxxxc8fe5010184

I have copied the folder with files from syssi in my folder ./homeassistant/xiaomi-miio-fan/.
Restarted Homeassistant, but still doesn't appear on the available service.

Did you do anything else ?guys ?

Thanks for your help

**Comment by MimbaMonkeyHouse** [comment]
This fan works with no issue. No battery reporting as indicated above... but the Mi Home app does not display this either. At present, there is no way to know the state of charge as there is also not led on the device like on the zhimi.fan.v3

**Comment by webhostsg** [comment]
> Hi guys,
> 
> I have also a model z4a but still error "Platform xiaomi_miio_fan not ready yet. Retrying in 180 seconds." I have retrieved the token from log file with mi home app 5.4.54, I have added the proper section in configuration.yaml
> 
> fan:
> 
> * platform: xiaomi_miio
>   host: 192.168.1.43
>   token: 4e990266227xxxxxxxxxxc8fe5010184
> 
> I have copied the folder with files from syssi in my folder ./homeassistant/xiaomi-miio-fan/.
> Restarted Homeassistant, but still doesn't appear on the available service.
> 
> Did you do anything else guys ?
> 
> For information I've added the Xiaomi vaccum with success, retrieving token with same method.
> 
> Thanks for your help

Try this in configuration.yaml:

```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.1.xxx
    token: 8e7023b1exxxxxxxxxxxxxxxx
    model: zhimi.fan.za4
```
