### ISSUE TITLE
Unsupported device found: zhimi.fan.za4 2.0.3 esp32

### ISSUE THREAD

**Issue by Anisse4** [syssi/xiaomi_fan#40]
Hi Syssi,

Thanks for your developpment on this Xiaomi fan integration.

I have a xiaomi fan 2S working with MiHome app. I am not able to integrate it in HA 0.97.2 despite of model already added by you in the supported list

I have copied the 2 *.py scripts and manifest.json in my folder .homeassistant/custom_components/xiaomi-miio-fan

I have installed python -miio with sudo pip3 install python-miio

I have retrieved the Token from log file with mi home app 5.4.54, and I have added the proper section in configuration.yaml:

platform: xiaomi_miio
name: Xiaomi Smart Fan
host: 192.168.1.43
token: 4e990266227xxxxxxxxxxc8fe5010184

Restarted Homeassistant, but still doesn't appear on the available service and get the error:

"Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.fan.za4"

Aug 20 11:37:31 raspberrypi hass[331]: 2019-08-20 11:37:31 INFO (MainThread) [homeassistant.components.xiaomi_miio.fan] Initializing with host 192.168.1.43 (token 4e990...)
Aug 20 11:37:31 raspberrypi hass[331]: 2019-08-20 11:37:31 INFO (MainThread) [homeassistant.components.xiaomi_miio.fan] zhimi.fan.za4 2.0.3 esp32 detected
Aug 20 11:37:31 raspberrypi hass[331]: 2019-08-20 11:37:31 ERROR (MainThread) [homeassistant.components.xiaomi_miio.fan] Unsupported device found! Please create an issue at https:/

For information I've added the Xiaomi vaccum with success, retrieving token with same method.

Thanks for your help

**Comment by syssi** [comment]
Your device will be supported soonish!

**Comment by syssi** [comment]
Oh, you've another problem. The custom component isn't regonized and HA is trying to use the official `xiaomi_miio` plattform which doesn't support this device. Please use this path and copy all files:

```
.homeassistant/custom_components/xiaomi_miio_fan/__init__.py
.homeassistant/custom_components/xiaomi_miio_fan/fan.py
.homeassistant/custom_components/xiaomi_miio_fan/manifest.json
```

And use this configuration:

```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.130.71
    token: b7c4a758c251955d2c24b1d9e41ce47d
```

Do you see the difference (`_fan`) at the platform name?

**Comment by Anisse4** [comment]
Thanks for your reply.

I have updated my folders and configuration file using a "_ '' . Restarting HA I have these errors messages

Log Details (ERROR)
Wed Aug 21 2019 10:44:07 GMT+0200 (Central European Summer Time)
Error executing service <ServiceCall homeassistant.restart (c:a339e3a92d4044b09ece6b71c906c848)>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1243, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/homeassistant/__init__.py", line 104, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 835, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/check_config.py", line 187, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 235, in get_platform
    "{}.{}".format(self.pkg_path, platform_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_fan/fan.py", line 3
    """ Support for Xiaomi Mi Smart Pedestal Fan. For more details about 
this platform, please refer to the documentation 
https://home-assistant.io/components/fan.xiaomi_miio/ """ import asyncio
                                                                         
                                                 
                                                    ^
SyntaxError: invalid syntax



And this error:
Log Details (WARNING)
Wed Aug 21 2019 10:44:06 GMT+0200 (Central European Summer Time)
You are using a custom integration for xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.


One question: Your folders and files should have specifics right/owner ?

Thanks for your support

**Comment by Anisse4** [comment]
> Oh, you've another problem. The custom component isn't regonized and HA is trying to use the official `xiaomi_miio` plattform which doesn't support this device. Please use this path and copy all files:
> 
> ```
> .homeassistant/custom_components/xiaomi_miio_fan/__init__.py
> .homeassistant/custom_components/xiaomi_miio_fan/fan.py
> .homeassistant/custom_components/xiaomi_miio_fan/manifest.json
> ```
> 
> And use this configuration:
> 
> ```
> fan:
>   - platform: xiaomi_miio_fan
>     name: Xiaomi Smart Fan
>     host: 192.168.130.71
>     token: b7c4a758c251955d2c24b1d9e41ce47d
> ```
> 
> Do you see the difference (`_fan`) at the platform name?

**Comment by Anisse4** [comment]
Thanks for your support, my bad, I had a copy past from my browser with some weired \n at each end of line.

So the updates about "_" has fixed my issue, the fan is properly recognised by HA.

Thanks again for your great job
