### ISSUE TITLE
Battery state on Xiaomi Standing Fan 2S

### ISSUE THREAD

**Issue by Leatherface75** [syssi/xiaomi_fan#41]
Component works but it doesn't show battery information and this one have battery.
Or maybe this model doesn't report that? Seems it's same in their own app.

**Comment by MimbaMonkeyHouse** [comment]
Got the same issue here and also note that Mi Home does not report battery state either. At present there is no way to know the battery charge neither on the device nor in the app!

**Comment by Leatherface75** [comment]
Yeah it's strange it does't have any information av about that in their own app either.

**Comment by d3wy** [comment]
I don't believe this is possible, the base of the fan contains the battery and offers simply two prongs for power up to the head unit similar to previous models, I don't believe the head unit (which contains all the wifi/controllers/etc) has the connectivity with the battery to report on it's state. The base simply has a battery which keeps outputting current until it runs flat.
