### ISSUE TITLE
Platform xiaomi_miio_fan not ready yet. Retrying in 180 seconds.

### ISSUE THREAD

**Issue by woinkeyman** [syssi/xiaomi_fan#51]
Hi - ran into the same issue as tribuneX -

Platform xiaomi_miio_fan not ready yet. Retrying in 180 seconds.
10:05 PM helpers/entity_platform.py (WARNING) - message first occurred at 9:49 PM and shows up 6 times
Unable to discover a device at address 10.123.8.167
10:05 PM custom_components/xiaomi_miio_fan/fan.py (ERROR) - message first occurred at 9:40 PM and shows up 6 times
Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
10:02 PM main.py (WARNING) - message first occurred at 9:40 PM and shows up 9 times
Got error when receiving: timed out
10:02 PM custom_components/xiaomi_miio_fan/fan.py (ERROR) - message first occurred at 9:41 PM and shows up 5 times

this is preventing the platform from working at all - any chance there are parts of the custom component i can fix? other components are fine contacting local IP addresses too.

**Comment by Bizzl** [comment]
I got this too - at first. Then I added the model type to the configuration. After that, Home Assistant presented me "Got error when receiving: timed out" as in issue #59 

Long story short: I had the wrong token. I originally extraced it from the current Mi Home app via the Hub-Card. The token shown there is not valid for the fan! I then uninstalled Mi Home, downloaded the old v5.4.49 (see https://www.home-assistant.io/integrations/xiaomi_miio#android-not-rooted - get the apk for example from apkmirror) and looked at the /Smarthome/logs directory at the intern memory. There I found a line with some JSON content, including an entry

{
   ...
   "token": "xyz",
   "name": "Smartmi Standing Fan 2S",
   ...
}

That token works like a charm!

**Comment by ipatalas** [comment]
I am experiencing the same issue now:
![image](https://user-images.githubusercontent.com/2623329/90821184-c8812c00-e332-11ea-824f-36dec79042a6.png)

Funny thing is.. right after I configured the integration it worked flawlessy. 
It was 2-3 days ago. Then next day it still worked and the day after that it just stopped working :(
I wasn't making any changes to the integration. I double checked if the token is correct. I have even restarted HA but no luck.
Any idea what else could help?
it used to work and now it doesn't. It still works via Mi Home app but that's not the point.

**Comment by syssi** [comment]
I'm closing this issue because it cannot be solved here.
