### ISSUE TITLE
Looking for the firmware of zhimi.fan.v2

### ISSUE THREAD

**Issue by countrysideboy** [syssi/xiaomi_fan#55]
I have a fan of zhimi.fan.v2. The spi flash is damaged. Can you please download the firmware by creating a hotspot and using wireshark to capture packets(When Mi Home shows that the fan could upgrade the firmware)?

I have another fan of zhimi.fan.v3, but the circuit is different from v2.

I'm sorry to send the help information here. I hope someone can help me. Thank you.

**Comment by syssi** [comment]
@rezmus Are you able to help here?

**Comment by rezmus** [comment]
http://cdn.cnbj0.fds.api.mi-img.com/miio_fw/15375c0437843d2456fb6ebce23c8a55_upd_zhimi.fan.v2.bin?Expires=1646722418000&GalaxyAccessKeyId=5721718224520&Signature=4gCZWbJRDCztmDohMYGOijMyTZY=

**Comment by countrysideboy** [comment]
Wow, thank you so much, @syssi and @rezmus !
I will try to modify the spi flash dump file of v3 with this firmware.
Is there another mcu firmware names mcuxxx.bin?

**Comment by rezmus** [comment]
i have only app_url part. do you have mcu file for zhimi.fan.v3?

**Comment by countrysideboy** [comment]
> i have only app_url part. do you have mcu file for zhimi.fan.v3? To be

Yes, I do. I think that app firmware could make my v2 fan work normally. Thank you again!
