### ISSUE TITLE
Add leshow.fan.ss4 support

### ISSUE THREAD

**Issue by deco3690** [syssi/xiaomi_fan#61]
I got a new xiaomi fan but this is seems to be unsupported. Would anyone be able to integrate? 

Log Details (ERROR)
Logger: custom_components.xiaomi_miio_fan.fan
Source: custom_components/xiaomi_miio_fan/fan.py:269
Integration: xiaomi_miio_fan (documentation)
First occurred: 6:22:05 PM (1 occurrences)
Last logged: 6:22:05 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: leshow.fan.ss4

**Comment by syssi** [comment]
Will be supported soon by: https://github.com/syssi/xiaomi_airpurifier/pull/134

**Comment by syssi** [comment]
The device is supported. Please give it a try!

**Comment by deco3690** [comment]
Very nicely done! Thank you!
