### ISSUE TITLE
python-miio dependancy

### ISSUE THREAD

**Issue by JamesMcCarthy79** [syssi/xiaomi_fan#63]
Hi there I thought I would let you know that any custom_component using the python-miio dependancy since 0.109.0 needs to use "python-miio>=0.5.0.1" otherwise it causes issues with any of the entities using the core integration (for me vacuum). I updated the manifest.json to "python-miio>=0.5.0.1" and this resolved the issue for me.

**Comment by Stormwarrior36** [comment]
How do you did that?

**Comment by JamesMcCarthy79** [comment]
@Stormwarrior36 navigate to your customer components folder `config\custom_components\xiaomi_miio_fan` and open the `manifest.json` and edit line 7 to the below
`"python-miio>=0.5.0.1"`

**Comment by Stormwarrior36** [comment]
Thank you. working fine now

**Comment by syssi** [comment]
Fixed.
