### ISSUE TITLE
Home Assistant 0.111 - value is not allowed for model

### ISSUE THREAD

**Issue by konnectedvn** [syssi/xiaomi_fan#64]
Used to work well on Home Assistant 0.110.

After upgrade to 0.111, it's failed with 'Invalid config for [fan.xiaomi_miio]: value is not allowed for dictionary value @ data['model']. Got 'zhimi.fan.za1':  (See ?, line ?).

**Comment by syssi** [comment]
Please update your `configuration.yaml`. This custom component isn't called `fan.xiaomi_miio` anymore.
