### ISSUE TITLE
A request in the support models. With heat module. Xiaomi MJXFJ-150-A1, Mjxfj-300-G1 ,XFXTDFR02ZM

### ISSUE THREAD

**Issue by wisesokol** [syssi/xiaomi_fan#65]
Hi.
Models of wall mounted. Input ventilation.
MJXFJ-150-A1
 Mjxfj-300-G1
XFXTDFR02ZM (newest model)

I have XFXT01ZM (no heat module) model.  It works perfectly with your component! 
`model: zhimi.airfresh.va2` 
![01](https://user-images.githubusercontent.com/48487551/84856599-d7680b80-b06f-11ea-90f0-879a1353cb3a.JPG)

I'll get a new model soon (XFXTDFR02ZM).
Will new devices work with this component?

**Comment by wisesokol** [comment]
For XFXTDFR02ZM integration zhimi.airfresh.va2 work fine but
1. Temperature instead of 25.5 it shows 2.55
2. no heater control

Otherwise it works fine.

**Comment by syssi** [comment]
The device is supported by https://github.com/syssi/xiaomi_airpurifier now.
