### ISSUE TITLE
Request to add new device dmaker.fan.p9

### ISSUE THREAD

**Issue by mac7500** [syssi/xiaomi_fan#66]
Recently I bought MIJIA DC Inverter Tower Fan . 
It's device model name is dmaker.fan.p9.
Could you add this model in supported device?

**Comment by maximatchev** [comment]
I'm very intrested in dmaker.fan.p9 too

**Comment by musk95** [comment]
Please add model dmaker.fan.p9.

**Comment by syssi** [comment]
The device is supported now by https://github.com/syssi/xiaomi_airpurifier/.
