### ISSUE TITLE
Improve Smartmi Standing Fan 3 (zhimi.fan.za5) support

### ISSUE THREAD

**Issue by zhenvw** [syssi/xiaomi_fan#69]
Hello, recently purchased a new fan (model: zhimi.fan.za5)
Can you add this model to supported devices? (zhimi.fan.za5)
What information do you need to provide to facilitate your work?
Thank you!

**Comment by wolverine28** [comment]
same here !

**Comment by RockyLim92** [comment]
is there any plan for supporting zhimi.fan.za5 or any workaround for supporting it?

Thank you

**Comment by darkiller22003** [comment]
Hi Sebastian,

Will you be adding in zhimi.fan.za5 ?
or do you have a tutorial on how to add unsupported devices?

**Comment by thangtrancb** [comment]
I also just bought 2 zhimi.fan.za5 fans, is there any way to add hassio?
Thankyou very much

**Comment by Chicoo** [comment]
Same here. I also just got a zhimi.fan.za5 and would like to have this added.

**Comment by pana800** [comment]
Please help with this new device with many thanks

**Comment by pana800** [comment]
Just to update. I tried  with model dmaker.fan.p21
And some of the functions works. On off, osscillation.
Hope this give some clues for a full function updates. 
Thanks

**Comment by syssi** [comment]
Cross link: https://github.com/syssi/xiaomi_airpurifier/issues/180

**Comment by syssi** [comment]
I would like to support this device soon. I would be happy about some support.

**Comment by pana800** [comment]
Thanks and looking forward to the new features

**Comment by syssi** [comment]
```
# https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:zhimi-za5:1

Device 'urn:miot-spec-v2:device:fan:0000A005:zhimi-za5:1': Fan with 7 services

* Service siid 1: (Device Information): 4 props, 0 actions

        ## Properties ##
                siid 1: piid: 1 (Device Manufacturer): (string, unit: None) (acc: ['read'])
                siid 1: piid: 2 (Device Model): (string, unit: None) (acc: ['read'])
                siid 1: piid: 3 (Device Serial Number): (string, unit: None) (acc: ['read'])
                siid 1: piid: 4 (Current Firmware Version): (string, unit: None) (acc: ['read'])

* Service siid 2: (Fan): 7 props, 0 actions

        ## Properties ##
                siid 2: piid: 1 (Switch Status): (bool, unit: None) (acc: ['read', 'write', 'notify'])
                siid 2: piid: 2 (Fan Level): (uint8, unit: none) (acc: ['read', 'write', 'notify'])
                        {'value': 1, 'description': '1'}
                        {'value': 2, 'description': '2'}
                        {'value': 3, 'description': '3'}
                        {'value': 4, 'description': '4'}
                siid 2: piid: 3 (Horizontal Swing): (bool, unit: None) (acc: ['read', 'write', 'notify'])
                siid 2: piid: 5 (Horizontal Angle): (uint16, unit: none) (acc: ['read', 'write', 'notify'])
                        Range: [30, 120, 1]
                siid 2: piid: 7 (Mode): (uint8, unit: none) (acc: ['read', 'write', 'notify'])
                        {'value': 0, 'description': 'Natural Wind'}
                        {'value': 1, 'description': 'Straight Wind'}
                siid 2: piid: 10 (Power Off Delay): (uint32, unit: none) (acc: ['read', 'write', 'notify'])
                        Range: [0, 36000, 1]
                siid 2: piid: 11 (Anion): (bool, unit: None) (acc: ['read', 'write', 'notify'])

* Service siid 3: (Physical Control Locked): 1 props, 0 actions

        ## Properties ##
                siid 3: piid: 1 (Physical Control Locked): (bool, unit: None) (acc: ['read', 'write', 'notify'])

* Service siid 4: (Indicator Light): 1 props, 0 actions

        ## Properties ##
                siid 4: piid: 3 (Brightness): (uint8, unit: percentage) (acc: ['read', 'write', 'notify'])
                        Range: [0, 100, 1]

* Service siid 5: (Alarm): 1 props, 0 actions

        ## Properties ##
                siid 5: piid: 1 (Alarm): (bool, unit: None) (acc: ['read', 'write', 'notify'])

* Service siid 7: (Environment): 2 props, 0 actions

        ## Properties ##
                siid 7: piid: 1 (Relative Humidity): (uint8, unit: percentage) (acc: ['read', 'notify'])
                        Range: [0, 100, 1]
                siid 7: piid: 7 (Temperature): (float, unit: celsius) (acc: ['read', 'notify'])
                        Range: [-30, 100, 0.1]

* Service siid 6: (用户自定义服务): 8 props, 0 actions

        ## Properties ##
                siid 6: piid: 1 (按下按键的键值): (uint8, unit: none) (acc: ['notify', 'read'])
                        {'value': 1, 'description': 'power'}
                        {'value': 2, 'description': 'swing'}
                        {'value': 0, 'description': '无按键按下'}
                siid 6: piid: 2 (是否有电池): (bool, unit: None) (acc: ['read', 'notify'])
                siid 6: piid: 3 (设定风扇水平转动7.5度): (string, unit: None) (acc: ['write'])
                siid 6: piid: 4 (当前扇叶实时转速，RPM。调试使用，不向用户开放。): (uint32, unit: None) (acc: ['read', 'notify'])
                        Range: [0, 3000, 1]
                siid 6: piid: 5 (交流电是否插入): (bool, unit: None) (acc: ['read', 'notify'])
                siid 6: piid: 6 (马达运行状况): (string, unit: None) (acc: ['notify'])
                siid 6: piid: 7 (lp-enter-second): (uint32, unit: seconds) (acc: ['write'])
                        Range: [1, 3600, 1]
                siid 6: piid: 8 (speed-level): (uint8, unit: none) (acc: ['write', 'read', 'notify'])
                        Range: [1, 100, 1]

        ## Events ##
                siid 6: eiid 1 (设备运行故障): (args: [6])
                siid 6: eiid 2 (childlock-trigger): (args: [])
```

**Comment by syssi** [comment]
```
# Anion?!

MODEL_FAN_ZA5: {
    # https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:zhimi-za5:1
    "power": {"siid": 2, "piid": 1},
    "fan_level": {"siid": 2, "piid": 2},
    "swing_mode": {"siid": 2, "piid": 3},
    "swing_mode_angle": {"siid": 2, "piid": 5},
    "mode": {"siid": 2, "piid": 7},
    "power_off_time": {"siid": 2, "piid": 10},
    "anion": {"siid": 2, "piid": 11},
    "child_lock": {"siid": 3, "piid": 1},
    "light": {"siid": 4, "piid": 3},
    "buzzer": {"siid": 5, "piid": 1},
    "humidity": {"siid": 7, "piid": 1},
    "button_pressed": {"siid": 6, "piid": 1},
    "battery_supported": {"siid": 6, "piid": 2},
    "speed_raw": {"siid": 6, "piid": 4},
    "powersupply_attached": {"siid": 6, "piid": 5},
    "temperature": {"siid": 5, "piid": 7},
    "fan_speed": {"siid": 6, "piid": 8},
},
```

**Comment by syssi** [comment]
I've pushed a basic

**Comment by syssi** [comment]
I've pushed basic ZA5 support. For now this features / properties are supported:

- [x] "power": {"siid": 2, "piid": 1},
- [x] "fan_level": {"siid": 2, "piid": 2}, (Level 1, Level 2 and Level 3. Level 4 is missing at the moment!)
- [x] "swing_mode": {"siid": 2, "piid": 3},
- [ ] "swing_mode_angle": {"siid": 2, "piid": 5},
- [x] "mode": {"siid": 2, "piid": 7},
- [x] "power_off_time": {"siid": 2, "piid": 10},
- [x] "anion": {"siid": 2, "piid": 11}, (implemented as buzzer. I don't know the meaning of `anion`)
- [x] "child_lock": {"siid": 3, "piid": 1},
- [ ] "light": {"siid": 4, "piid": 3},
- [ ] "buzzer": {"siid": 5, "piid": 1},
- [ ] "humidity": {"siid": 7, "piid": 1},
- [ ] "button_pressed": {"siid": 6, "piid": 1},
- [ ] "battery_supported": {"siid": 6, "piid": 2},
- [ ] "speed_raw": {"siid": 6, "piid": 4},
- [ ] "powersupply_attached": {"siid": 6, "piid": 5},
- [ ] "temperature": {"siid": 5, "piid": 7},
- [ ] "fan_speed": {"siid": 6, "piid": 8},

**Comment by pana800** [comment]
Thanks a lot. I replaced the new version and got this error
`Platform error fan.xiaomi_miio_fan - cannot import name 'Fan1C' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)`

**Comment by syssi** [comment]
@pana800 Which HA version do you use? Do you have additional custom components installed interfacing xiaomi devices? Please make sure every manifest.json is requiring the same python-miio version. Version `0.5.6` and HA core `2021.5.1` is required.

**Comment by pana800** [comment]
@syssi Thanks a lot for the advice,
I updated to HA 2021.5.1 and it worked. Great works.

**Comment by countrysideboy** [comment]
I also have this model.

Anion means the negative ion mode.

This fan have a so-called temperature-sensing mode(siid: 6, piid:10, ture or false)，i found the logic is:
 >28 degrees, 100% speed
>26, 74% speed
>=24, 35%
<24, 1%
It's useless and the Chinese ad says it's AI tuning speed mode.
I think we could add this mode if the model of the fan has a temperature sensor.

**Comment by jacobhallgren** [comment]
is it possible to get battery status the fan 3?

**Comment by jacobhallgren** [comment]
Yes and battery status would be nice

**Comment by nitobosch** [comment]
When trying to add and restard my home assistant i'm getting this error

`Logger: homeassistant.components.fan
Source: util/percentage.py:21
Integration: Ventilador (documentation, issues)
First occurred: 14:00:10 (2 occurrences)
Last logged: 14:00:10

Error adding entities for domain fan with platform xiaomi_miio_fan
Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 603, in state_attributes
    data[ATTR_SPEED] = self.speed
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 453, in speed
    percentage = self.percentage
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1155, in percentage
    return ordered_list_item_to_percentage(FAN_SPEEDS_1C, self._preset_mode)
  File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 21, in ordered_list_item_to_percentage
    raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
ValueError: The item "None"" is not in "['Level 1', 'Level 2', 'Level 3']"`

**Comment by filikun** [comment]
> 
> 
> When trying to add my new Smartmi Standing Fan 3, configuring on the configuration.yaml and restaring my home assistant i'm getting this error.
> 
> `Logger: homeassistant.components.fan
> Source: util/percentage.py:21
> Integration: Ventilador (documentation, issues)
> First occurred: 14:00:10 (2 occurrences)
> Last logged: 14:00:10
> 
> Error adding entities for domain fan with platform xiaomi_miio_fan
> Error while setting up xiaomi_miio_fan platform for fan
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
> await asyncio.gather(*tasks)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
> await entity.add_to_platform_finish()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
> attr.update(self.state_attributes or {})
> File "/usr/src/homeassistant/homeassistant/components/fan/**init**.py", line 603, in state_attributes
> data[ATTR_SPEED] = self.speed
> File "/usr/src/homeassistant/homeassistant/components/fan/**init**.py", line 453, in speed
> percentage = self.percentage
> File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1155, in percentage
> return ordered_list_item_to_percentage(FAN_SPEEDS_1C, self._preset_mode)
> File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 21, in ordered_list_item_to_percentage
> raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
> ValueError: The item "None"" is not in "['Level 1', 'Level 2', 'Level 3']"`

Same problem here

**Comment by fi-sch** [comment]
I am also willing to help with implementing the rest of device attributes. @syssi, please let me know if I can collect any helpful data for you.

**Comment by idantene** [comment]
With the latest HA and integration, I get this error:
```
2021-07-26 15:21:54 ERROR (MainThread) [homeassistant.components.fan] Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 666, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 455, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 607, in state_attributes
data[ATTR_SPEED] = self.speed
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 457, in speed
percentage = self.percentage
File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1157, in percentage
return ordered_list_item_to_percentage(FAN_SPEEDS_1C, self._preset_mode)
File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 21, in ordered_list_item_to_percentage
raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
ValueError: The item "None"" is not in "['Level 1', 'Level 2', 'Level 3']"
```

The `configuration.yaml` has:
```yaml
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Standing Fan 3
    model: zhimi.fan.za5
    host: XXX
    token: XXX
```

**Comment by DooMMasteR** [comment]
Yepp, same here.

**Comment by GauntPT** [comment]
> 
> 
> With the latest HA and integration, I get this error:
> 
> ```
> 2021-07-26 15:21:54 ERROR (MainThread) [homeassistant.components.fan] Error while setting up xiaomi_miio_fan platform for fan

I had the same issue. Removed the devices and reconfigured for three times. did not get it running.
What was helping in my case was to Turn Off the fan (not power off of course) and restart HA.

**Comment by GauntPT** [comment]
@syssi 
You have asked if someone is able to install custom python-miio on linux system. 
I have the fan ZA5 here (as well as 1X) as well the knowledge to do it (I believe)
I would be happy to help to push this fan to its limit  :)

Top priority for myself would be: Level 4 support and Oscillate Left / Right 5 degree

**Comment by idantene** [comment]
I managed to get the fully functionality by incorporating the changes here - https://github.com/rytilahti/python-miio/pull/1087/files

I can make a PR with the hard-coded values (which should then be needed to clean up once the above PR is merged).

**Comment by idantene** [comment]
In the meantime, a quick-and-dirty solution (done with vim 😛 my apologies) is attached.
Some notes for those who end up using it (and for @syssi if you end up taking it from here) -
1. For users - the following attributes have mock values (these should be removed when properly added): `battery_charge`, `use_time`, and potentially also `battery_state` (not sure what should be the proper values?), `led` (same, not sure about the proper values)
2. For developers - the current ad-hoc implementation abuses the `XiaomiFanMiot` by overloading many of `FanStatusZA5` with duplicate properties (instead of renaming/setting an attribute table with a dedicated class). Similarly, a lot of the previous code for ZA5 - now unused - is not cleaned up.

Temporary install notes:
1. Copy the code from the link below and replace `/config/custom_components/xiaomi_miio_fan/fan.py` with it
2. Restart HASS

[Modified fan.py](https://pastebin.com/tMn8uued)

**Comment by jonicunha** [comment]
> With the latest HA and integration, I get this error:
> 
> ```
> 2021-07-26 15:21:54 ERROR (MainThread) [homeassistant.components.fan] Error while setting up xiaomi_miio_fan platform for fan
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
> await asyncio.gather(*pending)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
> await asyncio.gather(*tasks)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
> await entity.add_to_platform_finish()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 666, in add_to_platform_finish
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 455, in _async_write_ha_state
> attr.update(self.state_attributes or {})
> File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 607, in state_attributes
> data[ATTR_SPEED] = self.speed
> File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 457, in speed
> percentage = self.percentage
> File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1157, in percentage
> return ordered_list_item_to_percentage(FAN_SPEEDS_1C, self._preset_mode)
> File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 21, in ordered_list_item_to_percentage
> raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
> ValueError: The item "None"" is not in "['Level 1', 'Level 2', 'Level 3']"
> ```
> 
> The `configuration.yaml` has:
> 
> ```yaml
> fan:
>   - platform: xiaomi_miio_fan
>     name: Xiaomi Standing Fan 3
>     model: zhimi.fan.za5
>     host: XXX
>     token: XXX
> ```

I have the same error. What have you done to bypass it?

**Comment by idantene** [comment]
> I have the same error. What have you done to bypass it?

@jonicunha, see my comment [above](https://github.com/syssi/xiaomi_fan/issues/69#issuecomment-887831736). The current implementation is lacking and I've provided a drop-in replacement that adds full functionality for the Smartmi Standing Fan 3. I believe @syssi will make the necessary updates to the integration soon enough, but until that time you can use the ad-hoc solution.

**Comment by EvilVir** [comment]
Hi guys,

I did some changes to the @idantene solution, which you can [find here](https://pastebin.com/XGUUBpkK).

First of all there was some bug that caused `preset_modes_override` to be ignored - fixed that.
Second improvement is that now slider for the fan speed operates in 0-100 range, allowing to use major feature of this fan - exact speed setting instead of choosing one of four presets.

Hope this will help and will make its way to the master :)

**Comment by syssi** [comment]
Please feel free to contribute your changes as pull request! :-)

**Comment by timconinx** [comment]
I just put the changes by @idantene and @EvilVir into a pull request referenced above this comment
