### ISSUE TITLE
Request to add support of dmaker.fan.p10

### ISSUE THREAD

**Issue by xcray** [syssi/xiaomi_fan#75]
could u pls add support to dmaker.fan.p5 (BPLDS02DM)?
Thanks for your cool repo!

**Comment by syssi** [comment]
You are asking for dmaker.fan.p10, right?

**Comment by xcray** [comment]
> You are asking for dmaker.fan.p10, right?

YES please, and Thanks! Sorry for mis-typing...

**Comment by kennychan0831** [comment]
also just got a new mi fan and found the model of it is p10 which now still not work in home assistant,plz add support of it! Thxxx

**Comment by lele1122** [comment]
same here, not working for dmaker.fan.p10

**Comment by syssi** [comment]
The device is supported now by https://github.com/syssi/xiaomi_airpurifier/.
