### ISSUE TITLE
Support model zhimi.fan.za5

### ISSUE THREAD

**Issue by heejoochae** [syssi/xiaomi_fan#77]
Here i got the error messages

Log Details (ERROR)
Logger: custom_components.xiaomi_miio_fan.fan
Source: custom_components/xiaomi_miio_fan/fan.py:278
Integration: xiaomi_miio_fan (documentation)
First occurred: 10:05:59 AM (1 occurrences)
Last logged: 10:05:59 AM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: zhimi.fan.za5

**Comment by wolverine28** [comment]
same here !

**Comment by syssi** [comment]
Duplicate of #69
