### ISSUE TITLE
Add additional property with natural mode 

### ISSUE THREAD

**Issue by damianpasek** [syssi/xiaomi_fan#80]
I would like to ask if it's possible to add additional property `natural_mode` to the list of available attributes? I would like to create switch for turning on/off the natural mode and I need for it state of `natural_mode`.

The value of this attribute is stored in `self._natural_mode`. I was trying to add it by myself but I was getting error that `FanStatus` does not have such property as `natural_mode`. I guess it's needed to add it in `python-miio`. 

Would it be possible do add such property?

**Comment by harrisony** [comment]
This might help you out
`switch:
  - platform: template
    switches:
      fan_natural:
        entity_id: fan.xiaomi_miio_fan
        icon_template: mdi:weather-windy
        value_template: >- 
          {{ state_attr('fan.xiaomi_miio_fan', 'natural_speed')|int > 0 }}
        turn_on:
          service: fan.xiaomi_miio_set_natural_mode_on
          data:
            entity_id: fan.xiaomi_miio_fan
        turn_off:
          service: fan.xiaomi_miio_set_natural_mode_off
          data:
            entity_id: fan.xiaomi_miio_fan
`

**Comment by TDK2525** [comment]
@harrisony - could you help out a HA newbie and specify where that should be entered and what might need to be locally specified?
