### ISSUE TITLE
Support device model dmaker.fan.p9

### ISSUE THREAD

**Issue by xrays72** [syssi/xiaomi_fan#83]
Hello, very please add support for dmaker P9
Maybe this link help for add support:
http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p9:1

**Comment by womeimingzi11** [comment]
Same here! I have got new dmaker P9 and dmaker P10, thanks for sharing.

**Comment by eholin** [comment]
Hi! I agree, it would be great if you added support for the dmaker.fan.p9 model. If there is any way to parse the fan protocol, please tell me, I'll try it.

**Comment by xrays72** [comment]
Hi.
@swim2sun, maybe after good work from this https://github.com/rytilahti/python-miio/pull/819 you can add support dmaker.fan.p9 in xiaomi_fan?

**Comment by swim2sun** [comment]
@xrays72 
Im working for support `dmaker.fan.p9/p10` because I have a xiaomi fan which model is `dmaker.fan.p10` ;)
I have tested my code for `dmaker.fan.p10`, it works.

 You can test it for your device by installing the following packages
[python_miio-0.5.3-py3-none-any.whl.zip](https://github.com/syssi/xiaomi_fan/files/5323756/python_miio-0.5.3-py3-none-any.whl.zip)

**Comment by xrays72** [comment]
@swim2sun thank you, this good news =)
ok, I'll try test this package, but I'm little bit know python =)

**Comment by anhnvme** [comment]
@syssi hello, can you update for p9/p10 ?.
It's already include at latest python-miio
https://github.com/rytilahti/python-miio/pull/819

**Comment by swim2sun** [comment]
Hi @anhnvme the PR is merged to `python-miio` but it's not released. I can create a PR for `syssi/xiaomi_fan` after `python-miio` released.

If you want to integrate new p9/p10 device now, pls refer to https://github.com/swim2sun/hass-config-milo/issues/1

**Comment by anhnvme** [comment]
> Hi @anhnvme the PR is merged to `python-miio` but it's not released. I can create a PR for `syssi/xiaomi_fan` after `python-miio` released.
> 
> If you want to integrate p9/p10 device now, pls refer to [swim2sun/hass-config-milo#1](https://github.com/swim2sun/hass-config-milo/issues/1)

Thanks you so much , I will try !!!!

**Comment by syssi** [comment]
The device is supported now by https://github.com/syssi/xiaomi_airpurifier/.
