### ISSUE TITLE
请问 米家变频落地扇2 是否支持？         "model" : "dmaker.fan.p11", 以后是否会支持？

### ISSUE THREAD

**Issue by lyf3** [syssi/xiaomi_fan#84]
请问 米家变频落地扇2 是否支持？         "model" : "dmaker.fan.p11", 以后是否会支持？

测试插件无法正常连接。dmaker.fan.p11

Logger: custom_components.xiaomi_miio_fan.fan
Source: custom_components/xiaomi_miio_fan/fan.py:279
First occurred: 下午6:25:19 (1 occurrences)
Last logged: 下午6:25:19

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p11

Logger: homeassistant.loader
Source: loader.py:315
First occurred: 下午6:24:19 (2 occurrences)
Last logged: 下午6:24:20

You are using a custom integration for xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
You are using a custom integration for HeWeather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by syssi** [comment]
The device is supported now by https://github.com/syssi/xiaomi_airpurifier/.
