### ISSUE TITLE
GitHub returned 404

### ISSUE THREAD

**Issue by HydrelioxGitHub** [syssi/xiaomi_fan#86]
When I try to add this repo as a custom repository in HACS, I get this error :

`GitHub returned 404 for https://api.github.com/repos/syssi/xiaomi_fan/`

**Comment by DeadHunter** [comment]
Which url did you use? Looks like you have a slash at the end.

Try: `https://github.com/syssi/xiaomi_fan`

**Comment by HydrelioxGitHub** [comment]
Yes it works without the slash. Thank you and sorry for wasting your time.
