### ISSUE TITLE
Right or left turn buttons do not work on zhimi.fan.v3, although they are visible on the card.

### ISSUE THREAD

**Issue by janfajessen** [syssi/xiaomi_fan#88]
Right or left turn buttons do not work on model zhimi.fan.v3 in the Home Assistant integration, although they are visible on the card. 
This is the atributes:

model
zhimi.fan.v3
angle
30
raw speed
691
delay off countdown
0
ac power
true
oscillate
false
direct speed
74
natural speed
0
child lock
false
buzzer
true
led brightness
0
use time
1500
temperature
28.6
humidity
66
battery
100
battery charge
complete
button pressed
-
led
-
battery state
-

**Comment by janfajessen** [comment]
Making a script does work

**Comment by syssi** [comment]
Could you provide a screenshot of the card? I'm not aware of this feature. Do you use a custom lovelace card?

**Comment by syssi** [comment]
@janfajessen If you use the buttons of the card which service is called?

**Comment by syssi** [comment]
Please update the custom component and try again. It should be working now.
