### ISSUE TITLE
fan.xiaomi_miio_set_oscillation_angle accepts strings only

### ISSUE THREAD

**Issue by syssi** [syssi/xiaomi_fan#9]
> fan.xiaomi_miio_set_oscillation_angle {"angle": 30} / {"angle": 60} / {"angle": 90} / {"angle": 120}

using numeric value seems to hang whole Hass.io :-/ passing string values works only for: "30", "60", "90", "120" for other values nothing happens and get this king of error: Invalid service data for fan.xiaomi_miio_set_oscillation_angle: value is not allowed for dictionary value @ data['angle']. Got '50'

https://github.com/syssi/xiaomi_fan/issues/4#issuecomment-394481632
@jacekpaszkowski

**Comment by syssi** [comment]
That's weird because the config schema evaluates a list of integeres:

```
SERVICE_SCHEMA_OSCILLATION_ANGLE = AIRPURIFIER_SERVICE_SCHEMA.extend({
    vol.Required(ATTR_ANGLE):
        vol.All(vol.Coerce(int), vol.In([30, 60, 90, 120]))
})
```

And the method signature expects an integer, too:

```
    async def async_set_oscillation_angle(self, angle: int) -> None:
```

Could you test it again with integers and may be debug log enabled?

I asked for testing some other values: For this tests the schema above must be extended temporary. Could a add the value `45` f.e., restart HA and try to call the service:

```
        vol.All(vol.Coerce(int), vol.In([30, 45, 60, 90, 120]))
```

```
fan.xiaomi_miio_set_oscillation_angle {"angle": 45}
```

Thanks for your support!

**Comment by MimbaMonkeyHouse** [comment]
Using  {"angle": 30} or  {"angle": 120} works fine here!

**Comment by syssi** [comment]
Could you extend the validation schema by "the" random value

```
SERVICE_SCHEMA_OSCILLATION_ANGLE = AIRPURIFIER_SERVICE_SCHEMA.extend({
    vol.Required(ATTR_ANGLE):
        vol.All(vol.Coerce(int), vol.In([10, 30, 60, 90, 120]))
})
```

and restart HA? This time the HA error "value is not allowed for dictionary value @ data['angle']." won't be triggered and the value ("10") will be passed to the device. I'm interested in the response of the device.

**Comment by syssi** [comment]
Thanks for your support. It looks like this feature works fine.
