### ISSUE TITLE
Does not work with device and home assistant on different subnets

### ISSUE THREAD

**Issue by jacobhallgren** [syssi/xiaomi_fan#90]
Hi

Does not work when fan is one subnet and home assistant is on another subnet. This works with the xiami vacum but not the fan.

Like fan is on 192.168.1.0/24
and home assistant on 10.46.2.0/24

**Comment by bfbones** [comment]
Got the same problem..

**Comment by syssi** [comment]
https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets

**Comment by syssi** [comment]
I will close the issue because it cannot be fixed here.
