### ISSUE TITLE
Custom element doesn't exist: fan-xiaomi

### ISSUE THREAD

**Issue by memphisraynz** [syssi/xiaomi_fan#98]
When opening the dashboard from the web or phone app, I get a red box saying "Custom element doesn't exist: fan-xiaomi".
This appears for a few seconds every time I access HA.

**Comment by syssi** [comment]
I assume your are using a custom **card**. Please raise an issue at the custom card repository. This is the repository of the custom component.

**Comment by memphisraynz** [comment]
Apologies, you are correct. Have a great day
