### ISSUE TITLE
Implement new fan model 

### ISSUE THREAD

**Issue by TheZoker** [syssi/xiaomi_fan#99]
@bdraco changed the fan model within HA:
https://github.com/home-assistant/core/pull/45407

Here is the architecture issue: 
https://github.com/home-assistant/architecture/issues/127

And an example for an adjusted integration:
https://github.com/home-assistant/core/pull/45767

Would be nice, if this custom integration could adapt the new model.

**Comment by bdraco** [comment]
@TheZoker This one might be helpful as well since it has preset modes

https://github.com/home-assistant/core/pull/45585

**Comment by syssi** [comment]
@bdraco Thanks for your great work! I will update the `xiaomi_miio` soon.
